### ISSUE TITLE
How can I override the build directory?

### ISSUE THREAD

**Issue by bschlenk** [gsoft-inc/craco#104]
I'm trying to override the build folder by changing `webpackConfig.output.path`, here is my `craco.config.js` file:

```js
const path = require('path');

const overrideWebpackConfig = ({ webpackConfig }) => {
  webpackConfig.output.path = path.resolve('my', 'custom', 'folder');
  return webpackConfig;
};

module.exports = {
  plugins: [
    {
      plugin: { overrideWebpackConfig }
    }
  ]
};
```

When running `craco build`, it works until the very end, when react-scripts tries to print out the  gzipped size of all the files. I get the error:

```
ENOENT: no such file or directory, open '/path/to/project/MyProject/build/static/css/main.16e7b84a.chunk.css'
```

This is still looking at the `build` folder, not `my/custom/folder`. Digging into it, react-scripts has this file `node_modules/react-scripts/config/paths.js` which is being used. Is there a way to modify this file using `craco`?

**Comment by bschlenk** [comment]
I just figured it out, the `context.paths` object can be modified:

```
const overrideWebpackConfig = ({ webpackConfig, context }) => {
  context.paths = webpackConfig.output.path = path.resolve('my', 'custom', 'folder');
  return webpackConfig;
};
```

Am I expected to be able to modify `context` here? I didn't see this documented anywhere.

**Comment by patricklafrance** [comment]
Hi @bschlenk 

No you can't modifie the context object, only the webpack config.

Craco doesn't support modifying the CRA paths because some are hardcoded.

You still can do it yourself by overriding the webpack, devServer and Jest config since you have access to the whole config objects.

Patrick

**Comment by spartakb** [comment]
Replying to an old thread here, but the following approach worked for me so maybe it will help someone searching for an answer in the future.   

```
const path = require('path');

module.exports = {
   webpack: {
        configure: (webpackConfig, { env, paths }) => { 
            paths.appBuild = webpackConfig.output.path = path.resolve('custom-build-dir');
        }
    }
}
```

PS: Any unexpected issues I should be aware of with this approach?

**Comment by shaoyanmin** [comment]
> ```
> const path = require('path');
> 
> module.exports = {
>    webpack: {
>         configure: (webpackConfig, { env, paths }) => { 
>             paths.appBuild = webpackConfig.output.path = path.resolve('custom-build-dir');
>         }
>     }
> }
> ```
@spartakb you should return `webpackConfig` in the end of the function. Then it works for me, thank you.
