### ISSUE TITLE
craco start with custom environment variables?

### ISSUE THREAD

**Issue by annjawn** [gsoft-inc/craco#116]
Is it possible to do a `craco start` with a custom environment variable?

For example `HOST_TYPE=nonprod craco start`

Is there any other recommended way? I want to be able to define scripts in my `package.json` so that I can use specific command for specific deployment like

```json
"scripts": {
    "start": "HOST_TYPE=dev craco start",
    "build": "HOST_TYPE=nonprod craco build",
    "prodbuild": "HOST_TYPE=prod craco build",
  }
```

I want to be able to use `process.env.HOST_TYPE` from within the app. There is the built in `process.env.NODE_ENV` but it is either `development` or `production` but I want to be able to identify multiple different environments so a custom environment variable will need to be used.

The technique shown above works with `react-scripts` but I haven't been able to make it work with `craco`. Is this something that can be achieved via the `craco.config.js`?

**Comment by patricklafrance** [comment]
Hi @annjawn 

You can override the the `NODE_ENV ` for the `start` and `test` scripts but not for the `build` script because CRA and React will optimize the output when the env is `production`.

If you want to add additional env var I suggest you use [cross-env](https://www.npmjs.com/package/cross-env).

Something like this will work:

```
"build:ci": "cross-env CI=true npm run build",
```

Hope it helps,

Patrick

**Comment by patricklafrance** [comment]
Also, for env var within the app, read this [documentation from CRA](https://create-react-app.dev/docs/adding-custom-environment-variables)

**Comment by annjawn** [comment]
Thanks. Yes I have gone through the React documentation but .env doesn't work for my case. My case is that I have 4 different environments. One is local development, then we have servers test, stage and production. Each have their own set of APIs configs etc. To add to complexity, we have CI Pipelines to ALL those environments from specific Git branches. What I want to achieve here is without overriding any built-in environment variable like `NODE_ENV` since that clearly doesn't work. I want to be able to define custom environment variable at build time like 

`"build:test":"HOST_TYPE=test craco build` 

so that internally the app evaluates `process.env.HOST_TYPE` to initialize proper configurations for that server (we have different config files for different environment like `dev.config.json`, `test.config.json`, `stage.config.json`, and `prod.config.json`). 

I have seen `cross-env` but I have not dived deeper with it. I will take a look at it.

**Comment by annjawn** [comment]
Ok i think i found what the issue is the custom Env var name needs to have `REACT_APP_` as prefix, like

`REACT_APP_HOST_TYPE=dev craco start`

then referring to it in the code `process.env.REACT_APP_HOST_TYPE` in the code works.
