### ISSUE TITLE
I had a crack at creating a favicons plugin

### ISSUE THREAD

**Issue by rickysullivan** [gsoft-inc/craco#118]
https://github.com/rickysullivan/craco-favicons

**Comment by rickysullivan** [comment]
Not yet on npm. Will wait for feedback (if any) before publishing soon.

**Comment by patricklafrance** [comment]
Hi @rickysullivan 

It looks good to me! Thank you!

Feel free to send a PR to add your plugin to the CRACO doc once you published it to NPM!
