### ISSUE TITLE
--config not working

### ISSUE THREAD

**Issue by codejamninja** [gsoft-inc/craco#124]
Craco is ignoring --config flag. I think the bug was introduced in the following commit.

https://github.com/gsoft-inc/craco/commit/ce0ba394b724f8de7d608eb4f003bb9089a4fc47

**Comment by patricklafrance** [comment]
Thanks for the issue!

I will try to release a fix this week.

**Comment by codejamninja** [comment]
Thanks

**Comment by patricklafrance** [comment]
Fix in https://www.npmjs.com/package/@craco/craco/v/5.6.2

**Comment by codejamninja** [comment]
@patricklafrance thanks
