### ISSUE TITLE
How to use environment variables/files ?

### ISSUE THREAD

**Issue by scorsi** [gsoft-inc/craco#126]
Hello,

I have a file `.env.production` and `.env.development`file with some variables into it.
I use them to change API url depending of the actual NODE_ENV.

```javascript
{
  "scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "craco eject"
  }
}
```
I tried using `cross-env` like : `cross-env NODE_ENV='development' craco start` without success.

How can I use my env files ?

Thanks,

**Comment by patricklafrance** [comment]
Does it work with CRA without CRACO?

CRA doc for env var: https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by scorsi** [comment]
Ok, I don't know why, really, but it's actually working now... 
Thanks for your time !

**Comment by ajaij** [comment]
@scorsi may I know how are you able to access "REACT_APP_FOO" from `.env.development` ? when importing inside craco.config.js am getting `undefined` as response.

```
/* .env.development */
REACT_APP_FOO="bar"

/* craco.config.js */
console.log('env....', process.env.REACT_APP_FOO);   // getting undefined here
```

**Comment by scorsi** [comment]
Hello @ajaij, this was pretty old :) 
I don't use it inside `craco.config.js` or imported js files (NodeJs part), I used it directly in the React code (the front part).

If you want to import the variables inside of theses craco files, you should import them directly. Maybe this package may help you : https://github.com/sholladay/envy or https://github.com/motdotla/dotenv

**Comment by ajaij** [comment]
got it @scorsi am facing issue using when am trying to use it inside the craco.config.js file, thank you for taking your time to respond to my query.
