### ISSUE TITLE
Wrong recipe css-modules

### ISSUE THREAD

**Issue by codefln** [gsoft-inc/craco#127]
This recipe doesn't work with CRA 3.3.0
https://github.com/gsoft-inc/craco/blob/master/recipes/use-babel-plugin-react-css-modules/craco.config.js

**Comment by patricklafrance** [comment]
I stop using the module a while ago.

Could you contribute an update for the recipe?

Thank you,

Patrick

**Comment by patricklafrance** [comment]
@codefln it might be related to https://github.com/gsoft-inc/craco/pull/130

**Comment by uiii** [comment]
Yes it doesn't work. Please fix it. I don't know how to fix, if I try to use the patter `[name]_[local]__[hash:base64:5]` it doesn't help, because the name is replace with `<filename>-module` but CRA uses only `<filename>` apparently.

**Comment by uiii** [comment]
Ahh, I've just upgraded craco to the latest version an it works fine.

**Comment by patricklafrance** [comment]
Awesome, I will the issue then.
