### ISSUE TITLE
Add support for JSON5

### ISSUE THREAD

**Issue by qub1n** [gsoft-inc/craco#131]
I would like to use comments in JSON using JSON5 extension like this:

const data = require('./data.json5');
export default data;

There is already json5-loader for this, but it seems to me that it cannot be used with a craco build unless it is somehow supported by a plugin.

I tried to add a module into config overwrites without any success:

config-overrides.js:

module.exports = {
    module: {
        rule:[{
            test: /\.json5$/,
            use: 'json5-loader',
            type: 'javascript/auto'
        }]
    }
};

I believe this feature request is very useful because it is always good to have comments in source code even if JSON is part of the source code.

**Comment by patricklafrance** [comment]
Hi @qub1n 

You're right without a webpack or babel plugin you need to configure either use CRACO [webpack.configure](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#configuration-overview) or build a [custom craco plugin](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#develop-a-plugin).

I think `config-override.js` is related to [react-app-rewired](https://github.com/timarney/react-app-rewired) which is another library.

If you want to develop a plugin for CRACO that only add a webpack loader to the config, it should be easy.

Something like:

```js
module.exports = {
    overrideWebpackConfig: ({ webpackConfig, cracoConfig, pluginOptions, context: { env, paths } }) => {
       webpackConfig.module.rules.push({
            test: /.json5$/,
            use: 'json5-loader',
            type: 'javascript/auto'
        });

        // Always return the config object.
        return webpackConfig;
    }
};
```

You can also have a look at the other [community maintained plugins](https://github.com/gsoft-inc/craco#community-maintained-plugins) for examples.

Hope it helps,

Patrick
