### ISSUE TITLE
Cannot override webpack's resolve

### ISSUE THREAD

**Issue by OnkelTem** [gsoft-inc/craco#132]
I created a `craco.config.js` with the following content:

```
module.exports = {
  mode: "extends",
  webpack: {
    resolve: {
      modules: ['node_modules', path.resolve(__dirname, 'src')]
    }
  }
}
```

And it didn't make any difference, paths are not resolved.
This is strange, because according to both webpack and craco documentation it MUST work.

Then I created my own plugin and it seems to work now:
```
module.exports = {
  plugins: [
    {
      plugin:  {
        overrideWebpackConfig: ({ webpackConfig }) => {
          webpackConfig.resolve.modules.push(path.resolve(__dirname, 'src'));
          return webpackConfig;
        }
      }
    }
  ]
};
```

But I believe it can be achieved using just plain config override, as it should be.

**Comment by patricklafrance** [comment]
Hi @OnkelTem,

No it's not diffectly supported, you need to either use

```

**Comment by OnkelTem** [comment]
@patricklafrance Oh, I see, thanks!
Then it might have been announced more clearly I believe :)

**Comment by mutheus** [comment]
> Hi @OnkelTem,
> 
> No it's not diffectly supported, you need to either use
> 
> ```
> module.exports = {
>   webpack: {
>         configure: (webpackConfig, { env, paths }) => { return webpackConfig; }
>   }
> }
> ```
> 
> or as you did, the plugin mecanism.
> 
> Docs for the config available here: https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#configuration-overview

Talking about the recipes, how could I override the `publicPath` e `historyApiFallback` to redirect all server requests to `/index.html`? I'm 1 day straight struggling with this. Could you help?
