### ISSUE TITLE
Missing changelog for 5.6.x

### ISSUE THREAD

**Issue by nirvdrum** [gsoft-inc/craco#134]
I just saw there was a 5.6.3 release and went to see what changed. It looks like the changelog fell out of date. There's nothing for the 5.6.x series at all in the `changelog/` directory. Fortunately, there weren't many commits between 5.6.2 and 5.6.3, so I could work that out by digging through the code. But, that process becomes a lot harder the more releases there are.

**Comment by patricklafrance** [comment]
Hi @nirvdrum 

Sorry, the original idea was to only add breaking changes to the changelog. This is quite sloppy. When I made this decision, CRACO was still my first OSS project and I did not care much about these concerns.

Learned a few tricks along the road. In the future, i'lll try to be more accurate and list all the changes in the matching Github release.

Thank you,

Patrick

**Comment by nirvdrum** [comment]
No problem. Thanks for putting this project together in the first place.
