### ISSUE TITLE
craco.config.js devServer.proxy is not work

### ISSUE THREAD

**Issue by lmlife2016** [gsoft-inc/craco#135]
my craco.config.js looks like the following:
```js
const path = require('path');

module.exports = {
    reactScriptsVersion: "react-scripts",
    style: {
        postcss: {
            mode: "extends",
            plugins: [
                require('postcss-camel-case'),
            ],
        }
    },
    webpack: {
        alias: {
            '@': path.join(path.resolve(__dirname, './src')),
        }
    },
    devServer: {
        proxy: {
            '/api': 'http://localhost:3001'
        }
    },
    // devServer: (devServerConfig) => {
    //     devServerConfig.proxy = {
    //         '/api': 'http://localhost:3001',
    //     };
    //     return devServerConfig;
    // }
};
```
my react app is running at http://localhost:3000

The result of requesting http://localhost:3000/api/get is ‘404(not found)’
![image](https://user-images.githubusercontent.com/23518009/72145835-42812800-33d6-11ea-9a80-950eb28fba2d.png)
		
But it's okay to request http://localhost:3001/get
![image](https://user-images.githubusercontent.com/23518009/72146062-aa377300-33d6-11ea-9b79-d31a7aac227a.png)

**Comment by patricklafrance** [comment]
Hi @lmlife2016 

I tried your config and I get the following output from CRACO:

```
{
  "disableHostCheck": true,
  "compress": true,
  "clientLogLevel": "none",
  "contentBase": "C:\\Dev\\20_gsoft\\craco-sandbox\\sandbox\\public",
  "watchContentBase": true,
  "hot": true,
  "transportMode": "ws",
  "injectClient": false,
  "publicPath": "/",
  "quiet": true,
  "watchOptions": {
    "ignored": {}
  },
  "https": true,
  "host": "0.0.0.0",
  "overlay": false,
  "historyApiFallback": {
    "disableDotRule": true
  },
  "public": "10.0.75.1",
  "proxy": {
    "/api": "http://localhost:3001"
  },
```

As you can see, the proxy section have been added to the resulting dev server config. Which make me thinks your problem is not with CRACO but somewhere else in your setup.

Thank you,

Patrick

**Comment by lmlife2016** [comment]
I checked and tried it again, and it worked, I'm confused. Anyway, thank you very much for your reply
