### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by rizkyramadhan** [gsoft-inc/craco#136]
$ craco start
internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module 'react-scripts/config/env.js'
Require stack:
- ~/node_modules/@craco/craco/lib/cra.js
- ~/node_modules/@craco/craco/scripts/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)

**Comment by patricklafrance** [comment]
Hi @rizkyramadhan 

It's hard to help you without more information about your setup.

Patrick

**Comment by rizkyramadhan** [comment]
nevermind, I forgot to yarn add react-scripts. Fixed when adding it.
