### ISSUE TITLE
source-map-explorer broken? Better/another way to analyse bundle size? 

### ISSUE THREAD

**Issue by rahulthewall** [gsoft-inc/craco#137]
I am trying to use source-map-explorer to visualise my bundle size, but that does not seem to be possible. Is there something wrong I am doing?

Here's my package.json (relevant part)

```
"analyze": "source-map-explorer 'build/static/js/*.js'",
"start": "craco start",
"build": "craco build"
```

The build/static/js directory has the following files

```
6.36295229.chunk.js                  HomePage.9519c3fc.chunk.js
6.36295229.chunk.js.LICENSE          HomePage.9519c3fc.chunk.js.map
6.36295229.chunk.js.map              PlaygroundPage.fa8d7808.chunk.js
7.42251a0a.chunk.js                  PlaygroundPage.fa8d7808.chunk.js.map
7.42251a0a.chunk.js.map              TasksPage.b905a08b.chunk.js
8.c4865b11.chunk.js                  TasksPage.b905a08b.chunk.js.map
8.c4865b11.chunk.js.map              main.8585f0c4.chunk.js
9.c95cf934.chunk.js                  main.8585f0c4.chunk.js.map
9.c95cf934.chunk.js.map              runtime-main.227e47d1.js
DevPage.5438f4d3.chunk.js            runtime-main.227e47d1.js.map
DevPage.5438f4d3.chunk.js.map
```

I then run source-map-explorer, but it doesn't seem to be doing anything. It's stuck at the following message

```
> @zyx/webapp@0.1.0 analyze /Users/xyz/code/trlabs_treat/packages/webapp
> source-map-explorer 'build/static/js/*.js'
```

Is there a better way to analyse bundle size with craco?

**Comment by patricklafrance** [comment]
Hi @rahulthewall,

I am no expert with using source-map-explorer but I do not believe craco add any constraint to the tool usage. I'm I wrong?

Patrick

**Comment by rahulthewall** [comment]
Hi @patricklafrance,

Apparently it just takes really long (nearly an hour). But it works. :)
