### ISSUE TITLE
syntax error on craco build

### ISSUE THREAD

**Issue by manishmawat** [gsoft-inc/craco#138]
Informations

Node.js version: v8.0.0
npm version: 5.0.0
nvm:1.1.7
Operating system: Windows 10
What is the current behavior?
syntax error on craco build pointing the toward spread operator (...)

craco.config.js:

``` 
module.exports = {
  webpack: {
    configure: (webpackConfig, { env, paths }) => {
      webpackConfig.output = {
<line 13>        ...webpackConfig.output,
        filename: 'scripts/index.js',
        chunkFilename: 'chunks/[name]_[chunkhash].js',
        publicPath: env === 'production' ? '/-/media/Foundation/XA-Extensions/REACT/REACT/' : '/',
      };
-
-
-
``` 
package.json:
```
"scripts": {
    "start": "npm run storybook:start",
    "dev": "craco start",
    "build": "craco build",
    "dist": "npm run build && del-cli build/*.* build/fonts",
    "test": "craco test",
    "lint": "eslint . --ext .js,.jsx --ignore-path .gitignore",
    "eject": "react-scripts eject",
-
-
-
```

Steps:
- Running "npm run build"  command which is triggering "craco build" and getting below error.

Error:-

``` 
craco.config.js:13
           ... webpackConfig.output,
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```
![image](https://user-images.githubusercontent.com/27475666/73395177-f88cb300-42ac-11ea-93a2-2fde2ed024cd.png)

**Comment by patricklafrance** [comment]
I don't know how to help you with the information you currently provide.

**Comment by manishmawat** [comment]
@patricklafrance : Added more information. 
Initially it was not recognizing craco so I installed craco "npm install @craco/craco". Now the craco is there but giving syntax error on build.

**Comment by manishmawat** [comment]
it related to the node version, I had node version 8.0.0 and ... (spread operator) is part of ES6 and ES6 support node => 8.10. After moving to 8.17.0, I am able to build the solution.
Closing the issue.
