### ISSUE TITLE
How does craco optimize for prod?

### ISSUE THREAD

**Issue by marioliu** [gsoft-inc/craco#139]
I'm running into a bug where something works locally when using `craco start`, but fails when using `craco build`. Is there anything that `craco build` does that could be the issue?

**Comment by patricklafrance** [comment]
Hi @marioliu,

`craco build` other that calling create react app `build` script and setting the env to `production`.

Create react app `build` script is doing a bunch of stuff though, I suggest having a look at the following cra doc: https://create-react-app.dev/docs/production-build/
