### ISSUE TITLE
Not picking up config?

### ISSUE THREAD

**Issue by mraak** [gsoft-inc/craco#140]
Probably something I did wrong though I followed a guide.

```
// craco.config.js
const path = require("path")
module.exports = {
  output: {
    chunkFilename: '[id]CCCCCC.js',
    path: path.resolve(__dirname, 'dist')
  }
}
```
```
//package.json
  "scripts": {
    "build": "craco build",
  },
```

Then I tried to build it:
```
C:\dev\projects\myApp>npm run build

> myApp build C:\dev\projects\myApp
> craco build

  540.62 KB  build\static\js\main.97530591.chunk.js
  333.75 KB  build\static\js\2.4b6e91f0.chunk.js
  7.44 KB    build\static\css\main.0eb1ccc4.chunk.css
  775 B      build\static\js\runtime-main.9d14031a.js


```

But it still gets built into the `build` folder, not `dist`, and neither do chunks have CCCCCC in the name. I tried few other settings like filename, but also not picking up.

**Comment by patricklafrance** [comment]
Hi @mraak.

Modifying paths is not supported by CRACO.

Thank you,

Patrick

**Comment by patricklafrance** [comment]
If you still want to do it, I suggest you use override the webpack config manually using:

```
module.exports = {
    webpack: {
        configure: { /* Any webpack configuration options: https://webpack.js.org/configuration */ },
        configure: (webpackConfig, { env, paths }) => { return webpackConfig; }
    }
}
```

The following should work:

```
module.exports = {
    webpack: {
        configure: {
               output: {
                    chunkFilename: '[id]CCCCCC.js',
                    path: path.resolve(__dirname, 'dist')
                 }
        }
    }
}
```

More info at: https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#configuration-overview

**Comment by mraak** [comment]
@patricklafrance So I guess I can't either prevent the splitting? The original intent was to use CRACO to build everything in only a single file - bundle.js or similar.

**Comment by mraak** [comment]
@patricklafrance The solution above is doing something but breaking the build. In any case what I wanted to override the config for was to prevent the splitting into chunks.

Tinkering with this now, making some progress, but do you happen to know exact config to prevent splitting?

```
module.exports = {
  webpack: {
    configure: {
      output: { filename: "static/js/[name]-build.js" },
      optimization: {
        runtimeChunk: false,
        splitChunks: {
          cacheGroups: {
            default: false,
          },
        },
      },
    },
  },
}

```

**Comment by patricklafrance** [comment]
Hi @mraak 

What is the error?

Does the error is related to craco or a bad webpack config?

If you need to use a different config base on the build /env, you can configure a different craco config file for dev or build script or you can leverage craco env utilities: https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#when-whendev-whenprod-whentest

**Comment by mraak** [comment]
@patricklafrance 

```
const path = require("path")
module.exports = {
  webpack: {
      configure: {
             output: {
                  chunkFilename: '[id]-ASDF.js',
                  path: path.resolve(__dirname, 'dist')
             }
      }
  }
}
```

So applying this output config results in the following. 
- First the build folder gets created and CRA starts building there
- Then also the `dist` folder gets created
- Then the build fails with the following error:
`ENOENT: no such file or directory, open 'C:\dev\projects\myApp\build\0-ASDF.js'`
- It looks like `build/static/js` has no chunks and no webpack compiled js, these went into `dist` root

So obviously this output config only deals with the chunk compilation, not the whole CRA output.

**Comment by patricklafrance** [comment]
Hi @mraak 

I am not sure how to help you on this.

The goal of CRACO is to give you the ability to update the webpack config of CRA which seems to be fine at the point.

I guess you need to update some other pieces of the webpack config to make this work but I can't tell which one.

Patrick

**Comment by mraak** [comment]
Yep, agreed. It's the tweaking of config that has to be figured out.

**Comment by bihongbin3027** [comment]
- module.exports = {
-     webpack: {
-     configure: {
-       output: {
-         path: path.resolve(__dirname, 'dist'),
-         filename: '[name].js',
-       },
-     },
-   },
- }

**Comment by wangweijia** [comment]
@mraak
how to fix?
