### ISSUE TITLE
Tslint ignores not respected

### ISSUE THREAD

**Issue by varghesethomase** [gsoft-inc/craco#141]
I am using craco version 5.6.3 along with react-scripts version 3.3.1 and found that no longer is typescript parser respecting the ts-ignore comments and throws error for each one of them. 
```
<ButtonComponent
      /*
      // @ts-ignore */
      className={`Button Button--with-loader ${className}`}
      {...passThroughProps}
    >
```

**Comment by patricklafrance** [comment]
Hi @varghesethomase 

I am not sure this a problem with CRACO.

What makes you think this is CRACO which introduces the problem?

**Comment by varghesethomase** [comment]
I believe it wasnt a problem with the craco either. Had a chance to fix this by solving a specific set of issues that showed up during the craco compilation which earlier hadnt shown up with react-scripts 3.3.1 though. Thanks for the quick reply @patricklafrance
