### ISSUE TITLE
npm run eject remove required modules

### ISSUE THREAD

**Issue by kristiandrex** [gsoft-inc/craco#142]
`npm run eject` remove react-scripts module that craco requires

![Screenshot](https://user-images.githubusercontent.com/26419041/74305391-c871f500-4d2d-11ea-9067-769795ac6a60.png)

**Comment by patricklafrance** [comment]
Hi @kristiandrex 

If you eject, you don't need CRACO anymore.

CRACO have been built to let you customize CRA without ejecting.

Thank you,

Patrick

**Comment by kristiandrex** [comment]
> Hi @kristiandrex
> 
> If you eject, you don't need CRACO anymore.
> 
> CRACO have been built to let you customize CRA without ejecting.
> 
> Thank you,
> 
> Patrick

Oh, thanks for the explanation.
