### ISSUE TITLE
How to disable CRA hot reload?

### ISSUE THREAD

**Issue by OnkelTem** [gsoft-inc/craco#143]
Would you please share a recipe of hot reload disabling?

**Comment by patricklafrance** [comment]
Hi @OnkelTem 

By looking at webpack devServer config it's like the 2 options you want to turn off are:

- `hot`:  https://webpack.js.org/configuration/dev-server/#devserverhot
- `inline`: https://webpack.js.org/configuration/dev-server/#devserverinline

So I would do this:

```
module.exports = {
   devServer: {
      hot: false,
      inline: false
   }
};
```

Hope it help!

Patrick

**Comment by patricklafrance** [comment]
Let me know if it works for you @OnkelTem, if it does I will create a recipe to share the knowledge.

**Comment by OnkelTem** [comment]
Ah, sorry @patricklafrance, I haven't worked on that project again yet, it's still on pause. I'll let you know soon!

**Comment by sarahhenkens** [comment]
I had a similar need today and the following config does not work, it still emits the hot-update files:
```
module.exports = {
  devServer: {
    writeToDisk: true,
    hot: false,
    inline: false,
    liveReload: false
  },
}
```

**Comment by shrekuu** [comment]
@sarahhenkens  Me too!  😅

I tried: 
```
devServer: {
    hot: false,
    inline: false,
    hotOnly: false,
    injectHot: false,
    liveReload: true,
  },
```

still not working.

**Comment by PiotrKozlowski** [comment]
I've tried different combinations of these settings, but it still didn't work:
```
webpack: {
    configure: {
      watch: false,
      devServer: {
        hot: false,
        inline: false,
        injectHot: false,
        liveReload: false,
        watchContentBase: false,
      },
    }
  },
  devServer: {
    hot: false,
    inline: false,
    injectHot: false,
    liveReload: false,
    watchContentBase: false,
  },
 ```
 I'm using `react-scripts@3.4.4` and `@craco/craco@5.8.0`
 
 I'll just try forking `react-scripts` as advised in [the documentation](https://create-react-app.dev/docs/alternatives-to-ejecting)

**Comment by dvcrn** [comment]
Ever figured this one out?

**Comment by dilanx** [comment]
The following craco config seems to work (at least on the latest alpha build). When these options are set, I notice that changes to source files do not take effect on the dev server.

```js
module.exports = {
    devServer: {
        hot: false,
        liveReload: false,
        watchFiles: [],
    },
}
```
