### ISSUE TITLE
Cannot kill WDS with CTRL+C with craco + >react-scripts@3.3.0

### ISSUE THREAD

**Issue by cjones26** [gsoft-inc/craco#148]
Hi,

After upgrading my react-scripts to version 3.3.0, I am no longer able to kill webpack-dev-server with CTRL+C.  After reverting to 3.2.0, I am no longer having any issues, and I am properly able to close WDS. I am running Windows 10, FYI.

Thanks!

**Comment by patricklafrance** [comment]
Hi @cjones26,

I doubt this problem is caused by CRACO, I suggest you create an issue on https://github.com/facebook/create-react-app

Patrick
