### ISSUE TITLE
Can I build my app into single js file?

### ISSUE THREAD

**Issue by DTX-92** [gsoft-inc/craco#155]
Tried this one, but it didn't help:
```
module.exports = {
   webpack: {
      configure: {
         optimization: {
            runtimeChunk: false,
            splitChunks: {
               cacheGroups: {
                  default: false,
               },
            },
         },
      },
   },
```

**Comment by dilakv** [comment]
Same issue.

**Comment by dilakv** [comment]
This worked for me.

Generate one file with css and one with js.

`

module.exports = {
  webpack: {
    configure: {
      output: {
        filename: 'main.js',
      },
      // externals: {
      //   react: {
      //     root: 'React',
      //     commonjs2: 'react',
      //     commonjs: 'react',
      //     amd: 'react',
      //     umd: 'react',
      //   },
      //   'react-dom': {
      //     root: 'ReactDOM',
      //     commonjs2: 'react-dom',
      //     commonjs: 'react-dom',
      //     amd: 'react-dom',
      //     umd: 'react-dom',
      //   },
      // },
      optimization: {
        runtimeChunk: false,
        splitChunks: {
          chunks: 'all',
          cacheGroups: {
            default: false,
            vendors: false,
            // vendor chunk
          },
        },
      },
    },
  },
  plugins: [
    {
      plugin: require('craco-plugin-scoped-css'),
    },
  ],
}

`

I don't know why i can't put this code between the tags code.

Sorry, i did try a lot of times

**Comment by gupta-ji6** [comment]
See [this](https://github.com/facebook/create-react-app/issues/5306#issuecomment-695173195) comment by @leoloso as well.

**Comment by vjsingh** [comment]
@gupta-ji6 Is this working in CRA 4? It's not working for me (commented on that thread as well, but realized it may be a craco issue and not a CRA issue).
