### ISSUE TITLE
Error: Cannot find module './lib/features/test/api'

### ISSUE THREAD

**Issue by Grawl** [gsoft-inc/craco#158]
Trying to add a loader.

Didn't find a recipe, found some snippets in issues.

Here's the code causing me an error:

```js
const { loaderByName, addBeforeLoader } = require("@craco/craco");
```

```
Error: Cannot find module './lib/features/test/api'
```

This file don't exist in my `node_modules`. Even `lib/features/test/` folder don't exist.

```
➜ ll node_modules/@craco/craco/lib/features
итого 12K
drwxr-xr-x. 2 grawl grawl 4,0K апр 14 17:48 dev-server
-rw-r--r--. 1 grawl grawl 4,0K апр 14 13:53 plugins.js
drwxr-xr-x. 3 grawl grawl 4,0K апр 14 17:48 webpack
```

**Comment by patricklafrance** [comment]
Hi Grawl,

Could it be your issue? https://github.com/gsoft-inc/craco/issues/144

**Comment by Grawl** [comment]
Yes.

**Comment by Grawl** [comment]
I just removed all 'tests' section from `.yarnclean`

[motivation here](https://github.com/gsoft-inc/craco/pull/145#issuecomment-615247938)
