### ISSUE TITLE
How to remove/replace webpack plugin?

### ISSUE THREAD

**Issue by etylsarin** [gsoft-inc/craco#159]
Hi @patricklafrance ,
is there an easy way, how to remove or replace a particular webpack plugin?
Thanks!

**Comment by patricklafrance** [comment]
Hi @etylsarin 

No there isn't. Since most plugins are object instances I haven't found a way to reliably identify a specific plugin in the webpack config plugins array.

**Comment by etylsarin** [comment]
well, I know that rescripts do it based on constructorName which works quite well: https://github.com/harrysolovay/rescripts#removewebpackpluginconstructorname-config

**Comment by etylsarin** [comment]
And also react-app-rewired has a plugin to do so: https://github.com/sigged/react-app-rewire-unplug

**Comment by patricklafrance** [comment]
@etylsarin thanks i'll have a look. Won't be this week though.

**Comment by etylsarin** [comment]
np, ty!

**Comment by alexasselin008** [comment]
Hi @etylsarin, you might want to take a look at the new craco version! https://github.com/gsoft-inc/craco/releases/tag/v6.1.0

**Comment by TomaszG** [comment]
@alexasselin008 could you provide an example of how to use it, please? I couldn't find any and documentation doesn't clearly say what should be put in `add`, `remove` arrays.

**Comment by patricklafrance** [comment]
It’a documented here https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#configuration-file

**Comment by etylsarin** [comment]
> Hi @etylsarin, you might want to take a look at the new craco version! https://github.com/gsoft-inc/craco/releases/tag/v6.1.0

Hi @alexasselin008 thanks for letting me know! :)
