### ISSUE TITLE
How can I turn on `requireEnsure` option?

### ISSUE THREAD

**Issue by chayeoi** [gsoft-inc/craco#160]
I am using [pdf.js](https://github.com/mozilla/pdf.js/) in my project.

When using this library with cra, the following output is displayed on the console.

(See [mozilla/pdf.js#10324 comment.](https://github.com/mozilla/pdf.js/issues/10324#issuecomment-447174852))

> Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

When ejected, this option is set as below.

```js
{
  module: {
    rules: [
      // Disable require.ensure as it's not a standard language feature.
      { requireEnsure: false },
    ],
  },
}
```

I would like to remove this option or change the value to `true` using craco without no ejecting. How can I do this?

**Comment by chayeoi** [comment]
I solved the issue by getting an existing webpack configuration object and returning a new configuration object.

```js
module.exports = () => ({
  webpack: {
    configure: (config) => {
      const [rule, ...restRules] = config.module.rules;

      return {
        ...config,
        module: {
          ...config.module,
          rules: restRules,
        },
      }),
    },
  }
};
```

**Comment by patricklafrance** [comment]
Sounds good to me, CRACO doesn't have anything out of the box for these specific use case.

If you feel like getting this a step further, you could write a small CRACO plugin to share the good with others.

Here's the docs for plugins: https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#develop-a-plugin
