### ISSUE TITLE
Adding uncompiled typescript library

### ISSUE THREAD

**Issue by stefansandulescu** [gsoft-inc/craco#162]
I have a "common library" written in Typescript and I want to use it in a couple more projects. I don't want to create a npm package from it, I just want to import it as "uncompiled package" but I'm having trouble setting this up.
I tried adding ```ts-loader``` and excluding the module like this:
```
webpackConfig.module.rules.push({
  test: /\.tsx?$/,
  use: 'ts-loader',
  exclude: /node_modules\/((?!common-library).)*$/,
});
```
However, this results in ```Error: TypeScript emitted no output for /path/to/index,tsx```.
Can I please get some guidance on this?
Thank you

**Comment by ranisalt** [comment]
@stefansandulescu can you give more information if you fixed the issue?

**Comment by stefansandulescu** [comment]
Hello,
I haven't fixed this. I ended up compiling the library.

**Comment by richardaum** [comment]
Is there any way to do it without compiling the library?
