### ISSUE TITLE
Extend resolve.extensions

### ISSUE THREAD

**Issue by asleepingpanda** [gsoft-inc/craco#163]
I am trying to extend webpack's resolve.extensions so that I can use the following file type: fileName.sandbox.js.

I've followed the documentation for setup and been ready through the API docs. I just can't seem to get anything to work. Before I go all out and build a plugin to do this, I wanted to check in and see if I'm missing something simple.

The things I've tried are:

``` 
module.export = {
    webpack: {
        resolve: {
            extensions: ['.sandbox.js', '.js'],
        },
    },
};

and

module.export = {
     resolve: {
            extensions: ['.sandbox.js', '.js'],
        },
};
```

Neither of which seem to work. I've always used base configurations for webpack. This is my first effort at extending/changing webpack configurations so any help/guidance would really, really appreciated!

Thanks

**Comment by asleepingpanda** [comment]
*** UPDATE ***

Reading through the documentation again, I think I understand that I was not at all configuring my craco.config.js correctly. Below is the code that I attempted, neither of which are working. What else am I missing? I feel like I'm so close to getting this!

```module.export = {
    webpack: {
        configure: (ogWebpack, { env, paths }) => {
            const webpackConfig = ogWebpack;
            if (!webpackConfig.resolve.extensions) {
                webpackConfig.resolve.extensions = [];
            }

            const { extensions } = webpackConfig.resolve;
            webpackConfig.resolve.extensions = [
                '.sandbox.js',
                ...extensions,
            ];

            return webpackConfig;
        },
    },
    plugins: [
        {
            plugin: {
                overrideWebpackConfig: ({
                    webpackConfig, cracoConfig, pluginOptions, context: { env, paths },
                }) => {
                    if (!webpackConfig.resolve.extensions) {
                        webpackConfig.resolve.extensions = [];
                    }

                    const { extensions } = webpackConfig.resolve;
                    webpackConfig.resolve.extensions = [
                        '.sandbox.js',
                        ...extensions,
                    ];

                    return webpackConfig;
                },
            },
        },
    ],
};```

**Comment by asleepingpanda** [comment]
... I'm so sorry... I was doing `module.export` instead of `module.exports` My bad!! Works perfectly!!

**Comment by patricklafrance** [comment]
Haha no worry, thanks for the update @asleepingpanda
