### ISSUE TITLE
help with using craco with docker

### ISSUE THREAD

**Issue by billtlee** [gsoft-inc/craco#165]
I am trying to get craco to work with my app which is running in a docker image.  For some reason after I install craco I am getting an error when running it saying there is a webpack conflict.  It's putting webpack 4.43.0 and react scripts requires 4.42.0.

This is what I am getting when I run npm list webpack

/app # npm list webpack
app@0.1.0 /app
+-- craco@0.0.3
| `-- webpack@4.43.0 
`-- react-scripts@3.4.1
  `-- webpack@4.42.0 

does anyone know why this might be happening?  Thanks!

**Comment by patricklafrance** [comment]
Hi @billtlee 

As you can here https://github.com/gsoft-inc/craco/blob/master/packages/craco/package.json

CRACO doesn't have any dependencies on webpack. Maybe the problem is somewhere else in your setup?

Thank you,

Patrick

**Comment by billtlee** [comment]
Thanks for the reply Patrick.  It was a user error.  I missed the @ sign so it was installing another package.  But now when I try to launch the app using craco start the container just exits right away.  Seems like the non blocking issue but I don't know how to get around it.  Have you tried using this with docker?  If so, any tips on how to get it working correctly?  Thanks!

**Comment by patricklafrance** [comment]
I have not personally use it with docker. @yohanb do we host or compile our front end with a docker container?

**Comment by yohanb** [comment]
@patricklafrance no.  @billtlee can you show us the contents of the `dockerfile` and the ENTRYPOINT?

**Comment by billtlee** [comment]
Hi Yohan,

 

Here is our docker file:

 

FROM node:12-alpine

RUN apk --no-cache add --virtual builds-deps build-base python

RUN npm install -g nodemon

WORKDIR /app

COPY package.json /app/package.json

RUN npm install

COPY . /app

USER node

CMD ["npm", "run", "start"]

**Comment by billtlee** [comment]
Hi Yohan,

 

Here is our docker file:

 

FROM node:12-alpine

RUN apk --no-cache add --virtual builds-deps build-base python

RUN npm install -g nodemon

WORKDIR /app

COPY package.json /app/package.json

RUN npm install

COPY . /app

USER node

CMD ["npm", "run", "start"]

 

 

Here is our package.json

{

  "name": "app",

  "version": "0.1.0",

  "private": true,

  "dependencies": {

    "@antv/data-set": "^0.11.4",

    "@craco/craco": "^5.6.4",

    "@material-ui/core": "^4.10.0",

    "@material-ui/icons": "^4.9.1",

    "@testing-library/dom": "7.5.7",

    "@testing-library/jest-dom": "^4.2.4",

    "@testing-library/react": "^9.3.2",

    "@testing-library/user-event": "^7.1.2",

    "axios": "^0.19.2",

    "bizcharts": "^4.0.3",

    "cookie-parser": "^1.4.5",

    "crypto-js": "^4.0.0",

    "history": "^4.9.0",

    "jsencrypt": "^3.0.0-rc.1",

    "lodash": "^4.17.15",

    "perfect-scrollbar": "^1.4.0",

    "qs": "^6.9.4",

    "react": "^16.13.1",

    "react-bootstrap-sweetalert": "^5.1.9",

    "react-csv": "^2.0.1",

    "react-dom": "^16.13.1",

    "react-dropzone": "^11.0.1",

    "react-redux": "^7.0.2",

    "react-router-dom": "^5.2.0",

    "react-scripts": "3.4.1",

    "react-select": "^3.0.8",

    "react-star-rating-component": "^1.4.1",

    "redux": "^4.0.5",

    "redux-thunk": "^2.3.0",

    "shuffle-seed": "^1.1.6"

  },

  "devDependencies": {

    "node-sass": "^4.14.1",

    "nodemon": "2.0.4",

    "prop-types": "^15.7.2",

    "redux-devtools-extension": "^2.13.8"

  },

  "scripts": {

    "start": "craco start",

    "dev": "nodemon craco start",

    "build": "craco build",

    "test": "craco test"

  },

  "eslintConfig": {

    "extends": "react-app"

  },

  "browserslist": {

    "production": [

      ">0.2%",

      "not dead",

      "not op_mini all"

    ],

    "development": [

      "last 1 chrome version",

      "last 1 firefox version",

      "last 1 safari version"

    ]

  }

}

 

 

Here is the section on our docker-compose.yml

 

  clientv1:

    build:

      dockerfile: Dockerfile.dev

      context: ./app

    volumes:

      - /app/node_modules

      - ./app:/app

    tty: true

 

Best regards,

 

Bill

**Comment by yohanb** [comment]
@billtlee you're starting the app in development mode with `npm start`and this uses the development server.  Can you provide the logs of the failed container?

**Comment by yohanb** [comment]
this might be of interest: https://www.robinwieruch.de/docker-create-react-app-development

**Comment by billtlee** [comment]
@yohanb I finally got it to work.  I added tty: true to my docker file.  Although the logging behavior is a bit annoying now so a bit harder to debug.  The container wasn't failing, npm just calls craco and as soon as it hands off to craco it considered it as a success and exit with an exit code of 0.  If you guys figure out another way to get this to work, please let me know.  Thanks!

**Comment by yohanb** [comment]
@billtlee good news!  I'm surprised you had to do that... might have to do with the fact that it's in dev mode.  Personally I would build the production assets and run it with a different web server like express or nginx.

**Comment by billtlee** [comment]
I am using nginx for production.  Wanted to use nodemon for development.

**Comment by gregoryforel** [comment]
> @yohanb I finally got it to work. I added tty: true to my docker file, then run docker-compose using a -d flag. Although the logging behavior is a bit annoying now so a bit harder to debug. The container wasn't failing, npm just calls craco and as soon as it hands off to craco it considered it as a success and exit with an exit code of 0. If you guys figure out another way to get this to work, please let me know. Thanks!

Hi @billtlee , I'm facing the same issue, but not very well versed with docker. Would you be so kind to share your configuration (docker / docker-compose) please?

**Comment by billtlee** [comment]
Hi @gregoryforel, I am not very good at docker either.  But I will try my best.

Here is my docker file for the client service:

```
FROM node:12-alpine
RUN apk --no-cache add --virtual builds-deps build-base python
RUN npm install -g nodemon
WORKDIR /app
COPY package.json /app/package.json
RUN npm install
COPY . /app
USER node
CMD ["npm", "run", "dev"]
```

In my package.json I have 

`"dev": "nodemon craco start"`


Here is the client section in my docker-compose.yml

```
  clientv1:
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    volumes:
      - /app/node_modules
      - ./app:/app
    tty: true
```
notice the last line tty: true.  This is what made it work.  However the terminal logging is acting a bit strange.  Debugging is not as easy as before.

Hope this helps.

**Comment by gregoryforel** [comment]
That's great! Was able to make it work as well. Thank you so much!

**Comment by billtlee** [comment]
Glad I can help.  To get around the terminal logging, I am now starting each service individually in multiple terminal tabs as such:

docker-compose up serviceName

**Comment by gregoryforel** [comment]
Thanks. I'll pass this info to the team!

**Comment by stepanBoichyshyn** [comment]
' tty: true'
in docker-compose helped me
