### ISSUE TITLE
 Support for the experimental syntax 'decorators-legacy' isn't currently enabled

### ISSUE THREAD

**Issue by renleiabc** [gsoft-inc/craco#166]

**Comment by renleiabc** [comment]
![image](https://user-images.githubusercontent.com/24283195/83322717-92c92b80-a28c-11ea-8990-35f664fa2bd7.png)
Using mobx and craco in projects,How to configure？

**Comment by patricklafrance** [comment]
https://github.com/gsoft-inc/craco/blob/master/recipes/use-mobx/craco.config.js

**Comment by MrMeiyu** [comment]
@renleiabc hi! Have you solved the problem?
