### ISSUE TITLE
How to modify appBuild path

### ISSUE THREAD

**Issue by JessicaDuan** [gsoft-inc/craco#168]
The default path is 'build', but I want to change it into something else, how can I do it in craco?

**Comment by patricklafrance** [comment]
Hi @JessicaDuan 

Not currently :(

**Comment by JessicaDuan** [comment]
> Hi @JessicaDuan
> 
> Not currently :(

okay, temporarily maybe I'll use
`"build": "craco build && mv build anotherBuild"`
thanks for your reply

**Comment by LuHugo** [comment]
#175
