### ISSUE TITLE
Failed to configure webpack entry

### ISSUE THREAD

**Issue by chentianxin** [gsoft-inc/craco#169]
```
// craco.config.js
const path = require('path');
const { env: { NODE_ENV } } = process;

module.exports = {
  webpack: {
    configure: {
      entry: path.resolve(__dirname, './src/main.js'),
      resolve: {
        alias: {
          '@': path.resolve(__dirname, './src'),
        },
      },
      devtool: NODE_ENV === 'development' ? 'eval-source-map' : 'hidden-source-map',
    },
  },
}


// terminal
// -> yarn start
// <- $ craco start
// <- Could not find a required file.
// <-  Name: index.js
// <-  Searched in: E:\projects\react-doc\src
// <- error Command failed with exit code 1.
// <- info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by patricklafrance** [comment]
Hi @chentianxin 

It doesn't seem to be an error related to CRACO.

CRACO let you customize CRA config but it is your responsibility to provide valid config.

Patrick

**Comment by tamb** [comment]
@patricklafrance I am running into a similar issue.  Most of my aliases work.  Some of them don't.  I then try renaming them and they still fail.  I rewrite the definition so it's perfect and it fails still

**Comment by n3ps** [comment]
Same problem. The project doesn't use the `src` name and I can't reconfigure.

**Comment by patricklafrance** [comment]
Hey guys,

CRA seems to resolve the entry path, maybe you need to do something similar?

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L185
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/paths.js#L88

We don't update CRA entry path at GSoft, so this is not something we tried.

If you think it should be handled by CRACO and you know how, a PR is welcome.

Patrick

**Comment by n3ps** [comment]
Sorry I wasn't clear enough. Yes, CRACO works if the project has `src` like most projects do.

My problem is the project I inherited __does not__ use `src` for reasons I have not control over. If I could I'd simply rename it.

Anyway, so it looks like in CRA's code they hard-coded it to look for `src/index` and there's no easy way to override.

**Comment by patricklafrance** [comment]
Oh sorry I understand now.

Yes sadly in CRA they hardcoded a bunch of paths.
