### ISSUE TITLE
How to add script tag to final build depending on environment?

### ISSUE THREAD

**Issue by ashishsantikari** [gsoft-inc/craco#170]
Hello there,

I am looking for a decent/non-hacky approach to append a javascript file to the final built index.html file.
**Use Case**: Add _only-prod.js_ to _index.html_ when the _build environment_ is **production**.

**Current implementation**: Irrespective of the environment, add the script file to index.html, _which throws an error in dev mode as the file appended might be syntactically incorrect._ 

Below is the code snippet which I am experimenting with.

```
// craco.config.js

const { when, whenProd } = require('@craco/craco')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const HtmlWebpackTagsPlugin = require('html-webpack-tags-plugin')

module.exports = {
  webpack: {
    plugins: [
      new HtmlWebpackPlugin(),
      ...whenProd(
        () => [
          new HtmlWebpackTagsPlugin({
            tags: ['only-prod.js'],
            append: true,
          }),
        ],
        []
      ),
    ],
  },
}
```

Is this a correct way to implement what I am trying to achieve?

**Comment by patricklafrance** [comment]
Hi @ashishsantikari 

I am not familiar with the `html-webpack-tags-plugin` plugin but it seems pretty straightforward it should work if your public path + the tag name match an existing file.

As for how to do it with CRACO, using `whenProd` is the way to go.

Patrick

**Comment by ashishsantikari** [comment]
Okay. 

As per the doc, **mode** property can be either _extends_ or _file_. **mode** property is not applicable for webpack config as I can see in the API. So, does it extend or replaces the existing webpack configuration?

**Comment by patricklafrance** [comment]
The "mode" property is only available for the `style.postcss` and `eslint` sections and would be a complete override if you choose "file".

The current behavior is to concat the existing plugins with the new plugins.

**Comment by patricklafrance** [comment]
A smarter merge could be achieved is someone is willing to send a PR.

There is an issue here: https://github.com/gsoft-inc/craco/issues/159
