### ISSUE TITLE
Enabling Fast Refresh through craco?

### ISSUE THREAD

**Issue by AK-101111** [gsoft-inc/craco#171]
create-react-app most recently added the experimental functionality of Fast Refresh through the .env variable FAST_REFRESH=true (which didn't work)
What modifications are required in the craco config to enable this?

**Comment by patricklafrance** [comment]
Hi @AK-101111 

You can set the env variable as specified in CRA docs, it should work. You could also submit a PR to add support for fast refresh to CRACO.

Similar features are supported by this code: https://github.com/gsoft-inc/craco/blob/master/packages/craco/lib/features/dev-server/set-environment-variables.js

**Comment by AK-101111** [comment]
Thank u for your response @patricklafrance 
Regardless of setting the environment variable I could not get it Fast Refresh to play. 

On the other hand I imported @pmmmwh/react-refresh-webpack-plugin
and simply added it to the webpack plugins through CRACO and ... it worked!

**Comment by patricklafrance** [comment]
That's odd, does fast refresh work with a fresh CRA app?

**Comment by AK-101111** [comment]
Sorry for the late reply. 
Based on the docs, they support it.
https://github.com/facebook/create-react-app/blob/master/docusaurus/docs/advanced-configuration.md

**Comment by LuisRodriguezLD** [comment]
@AK-101111 Can you share your craco settings? I can't get the Fast Refresh to work

**Comment by bard** [comment]
Apparently not in the released create-react-app yet: https://github.com/facebook/create-react-app/issues/8678#issuecomment-636839360

**Comment by franxois** [comment]
craco doesn't support yet cra@next (v4) but you can have fast refresh using a plugin
