### ISSUE TITLE
Cant access .env variable in craco.config.js

### ISSUE THREAD

**Issue by sntptrck** [gsoft-inc/craco#180]
For my case i need use CRA env variables (https://create-react-app.dev/docs/adding-custom-environment-variables/) but i dont see any REACT_APP variables in process.env (but correctly works in app, not in config)

**Comment by robmarshall** [comment]
My issue is a little like that: https://github.com/gsoft-inc/craco/issues/184 Cannot work it out.

**Comment by ajaij** [comment]
Am facing the same problem, has anyone figured a way on how to pass dotenv values inside craco.config.js ?

**Comment by banagale** [comment]
@ajaij Not sure if this will help you but see this discussion on env var usage: #116

**Comment by ajaij** [comment]
@banagale thank you for trying to help me out, in my case the values are located in .env file & not in package.json like below.


```
/* .env */
REACT_APP_FOO="bar"

/* craco.config.js */
console.log('env....', process.env.REACT_APP_FOO);   // getting undefined here
```

**Comment by wabi91** [comment]
@ajaij 
Are you coding on window OS?

It's really weird that i get the same issue with you, but other developer who coding with mac and install same versions of craco, cra doesn't get the issue.
I'm suspecting it is an OS problem.

**Comment by ajaij** [comment]
Hey @wabi91 am using mac, I have not tried in windows OS though.

**Comment by wabi91** [comment]
@ajaij
Even though you are trying in Mac, it's really weird that it doesn't work. In my case, i had same versions of react-script and craco and same craco.config.js, Mac worked and Windows didn't work, so I doubted it.

Did you try below 2 list?
1. make craco config file clean > check REACT_APP_ prefix variable
```js
module.exports = {};
```

2. reinstall npm after delete node_modules and package-lock.json

**Comment by ajaij** [comment]
hey @wabi91 I tied your steps, am still getting undefined.

these are the versions I have
```
"@craco/craco": "^5.8.0",
"react-scripts": "^4.0.0",
```

**Comment by wabi91** [comment]
> ```
> "@craco/craco": "^5.8.0",
> "react-scripts": "^4.0.0",
> ```

@ajaij !?! Why do you use CRA4?
Have u checked [this issue about supporting cra4](https://github.com/gsoft-inc/craco/issues/205#issuecomment-715528156) ?

I'm not sure, carco its working with cra4
and in my case,
after trying this and that, i finally gave up and upgraded to CRA4 and abandoned CRACO.....

**Comment by ajaij** [comment]
@wabi91 I downgraded the versions to the following

```
"@craco/craco": "^5.6.4",
"react-scripts": "3.4.3",
```

event then am getting the same undefined issue.

Luckily **Nam Nguyen** has suggested a solution for my question in this thread https://github.com/gsoft-inc/craco/issues/198 which resolved my undefined issue.

**Comment by trickpattyFH20** [comment]
I used [this library](
https://github.com/djdmbrwsk/dotenv-cra) as a solution.

```
const dotenvCra = require('dotenv-cra');

dotenvCra.config();

console.log(REACT_APP_ENV) // logs correct values from .env.*
```

https://github.com/djdmbrwsk/dotenv-cra

**Comment by idurar** [comment]
I have same issue ; craco work perfectly with env variables ; 
All varaible should start with REACT_APP_
check here my starter react project with carco / antd  : [https://github.com/idurar/starter-antd-admin-crud-auth-mern/tree/master/frontend](https://github.com/idurar/starter-antd-admin-crud-auth-mern/tree/master/frontend)

**Comment by yxdYXD11123123** [comment]
什么都不用弄，.env文件中声明的变量，用上 "REACT_APP_" 前缀即可。
例如：REACT_APP_BASE_URL=http://localhost:8000

**Comment by mario-subo** [comment]
> 

Thank you, this worked! I shouldn't have bothered with all the other "solutions".

**Comment by mario-subo** [comment]
> You can also just require this from react scripts, as it will run the logic used to populate the environment variables from normal cra.
> 
> `require('react-scripts/config/env');`

Thank you, this worked! I shouldn't have bothered with all the other "solutions".

**Comment by Abyssknight** [comment]
> You can also just require this from react scripts, as it will run the logic used to populate the environment variables from normal cra.
> 
> `require('react-scripts/config/env');`

Work for me
