### ISSUE TITLE
add webpack configure is not success

### ISSUE THREAD

**Issue by mr-kings** [gsoft-inc/craco#181]
add webpack configure is not success
configure: (webpackConfig, { env, paths }) => { 

      webpackConfig = {
        ...webpackConfig,
        devtool: useSourceMap ? 'source-map' : 'none' ,
      }

      const oneOfRules = webpackConfig.module.rules.find(item => item.oneOf);

      oneOfRules.oneOf.push({
        test: lessRegex,
        exclude: lessModuleRegex,
        use: getStyleLoaders(
          {
            importLoaders: 3,
            sourceMap: useSourceMap,
          },
          'less-loader'
        ),
        // Don't consider CSS imports dead code even if the
        // containing package claims to have no side effects.
        // Remove this when webpack adds a warning or an error for this.
        // See https://github.com/webpack/webpack/issues/6571
        sideEffects: true,
      },
      // Adds support for CSS Modules, but using less
      // using the extension .module.less
      {
        test: lessModuleRegex,
        use: getStyleLoaders(
          {
            importLoaders: 3,
            sourceMap: useSourceMap,
            modules: {
              getLocalIdent: getCSSModuleLocalIdent,
            },
          },
          'less-loader'
        ),
      })

      return webpackConfig
    }

**Comment by xxyGoTop** [comment]
mark

**Comment by xxyGoTop** [comment]
how to do?
