### ISSUE TITLE
Using babel enviroment variables

### ISSUE THREAD

**Issue by robmarshall** [gsoft-inc/craco#184]
I am looking to implement [babel-plugin-react-remove-properties](https://www.npmjs.com/package/babel-plugin-react-remove-properties) but the CRACO config file only seems to mention added babel plugins directly into the babel plugin array. Doesnt seem to add plugins depending on the environment.

The plugin installation shows applying only to production as so:

```
{
  "env": {
    "production": {
      "plugins": [
        "react-remove-properties"
      ]
    }
  }
}
```

Is this possible with CRACO?

**Comment by robmarshall** [comment]
Anyone able to point me in the right direction? Or where to go to find this out?

**Comment by robmarshall** [comment]
Hey. Me again - wondering if anyone has ever done this? Or knows who to speak to?

**Comment by robmarshall** [comment]
I think I have found a solution: Use whenDev/whenProd: https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#when-whendev-whenprod-whentest

**Comment by robmarshall** [comment]
```
const { whenProd } = require('@craco/craco');

module.exports = {
    babel: {
        plugins: [
            ...whenProd(
                () => [
                    [
                        'react-remove-properties',
                        {
                            properties: ['data-testid']
                        }
                    ]
                ],
                []
            )
        ]
    }
};

```

**Comment by lodado** [comment]
you saved my day !

**Comment by JuliaGurina** [comment]
thank you very much for this solution!
