### ISSUE TITLE
Include information on where contributors can submit their new plugin

### ISSUE THREAD

**Issue by nicobrinkkemper** [gsoft-inc/craco#186]
I have skimmed the wiki but I couldn't find a place to submit the plugin I recently made. You can find it here
https://github.com/nicobrinkkemper/craco-csv-loader

It has been working out great for me in combination with `react-snapshot` to have a no-config (ok, a little bit of craco config) SSR setup, having a simple spreadsheet as data.

EDIT: Also, I would love some feedback on it. I might've missed something crucial, though it should be close to how the other plugins are setup. I made it default to just test for `.csv` files, on which I'm not sure if it is the right approach.

**Comment by patricklafrance** [comment]
Hi,

Sorry for the late reply.

You can add the plugin to this project README file.

Thank you

**Comment by nicobrinkkemper** [comment]
https://github.com/gsoft-inc/craco/compare/master...nicobrinkkemper:patch-1
