### ISSUE TITLE
how to access custom variables ( defined in .env ) in craco.config.js ?

### ISSUE THREAD

**Issue by Techiu** [gsoft-inc/craco#198]
I want to change the @antd-prefix in CracoAntDesignPlugin, like below:

```
/* craco.config.js */

module.exports = function () {
  console.log('env....', process.env.REACT_APP_ANTD_PREFIX);
  return {
    eslint: {
      enable: true,
      mode: 'file',
    },
    plugins: [
      {
        plugin: CracoAntDesignPlugin,
        options: {
          customizeTheme: {
            '@ant-prefix': process.env.REACT_APP_ANTD_PREFIX,
          },
          customizeThemeLessPath: path.join(
            __dirname,
            'src/styles/antd.theme.less'
          ),
        },
      },
```

REACT_APP_ANTD_PREFIX is already defined in .env, but I got ```undefined``` here. Is there any way to get the right result ?

**Comment by ajaij** [comment]
@patricklafrance am also facing this issue, any solution for this ?

**Comment by Techiu** [comment]
> @patricklafrance am also facing this issue, any solution for this ?

In my situation, REACT_APP_ANTD_PREFIX is not related to different environment, so I placed it into the package.json file instead.

So, in a tricky way. You can set different key in package.json. And use WhenDev or WhenProd in craco.config.js to access different value.

```
// package.json
"devPrefix": "antd",
"prodPrefix":  "foo"

// craco.config.js

const { whenDev, whenProd  } = require('@craco/craco');
const { devPrefix, prodPrefix} = require('./package');

... whenDev(() =>{
    ... devPrefix
})

... whenProd  (() =>{
    ... prodPrefix
})

```

**Comment by ajaij** [comment]
@Techiu thanks for the suggestion, here I have placed the config in my .env file and am trying to access the value inside craco.config.js like  the below.

```
/* .env */
REACT_APP_FOO="bar"

/* craco.config.js */
console.log('env....', process.env.REACT_APP_FOO);

```
In this case am still getting undefined in the console, are you getting the value by any chance ?

**Comment by robmarshall** [comment]
I think I have found a solution: Use whenDev/whenProd: https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#when-whendev-whenprod-whentest

**Comment by namnm** [comment]
Try: Install `dotenv` then add `require('dotenv/config')` at the top of your craco.config.js

**Comment by ajaij** [comment]
Thank you @namnm your tip resolved my undefined issue, thanks a ton.

**Comment by waantony** [comment]
> Try: Install `dotenv` then add `require('dotenv/config')` at the top of your craco.config.js

I did it, but I only got variables in `.env` file, I cannot got variables in `.env.development` or `.env.production` file, so what should i do?

**Comment by namnm** [comment]
@waantony Please read the documentation of dotenv:
https://github.com/motdotla/dotenv#options
https://github.com/motdotla/dotenv#what-happens-to-environment-variables-that-were-already-set

**Comment by ajaij** [comment]
@waantony if ur trying to implement this in CRA, you can try this pkg https://www.npmjs.com/package/dotenv-cra as well.

**Comment by pinggi** [comment]
If you use CRA, you can just import the react script that loads the env files.

After this line in your craco.config.js file:
```
require('react-scripts/config/env');
```

you will able to access the env vars defined in your env files.
