### ISSUE TITLE
Downstream Effects of a CRA Webpack 5 Release

### ISSUE THREAD

**Issue by banagale** [gsoft-inc/craco#201]
I was looking to build a plugin in craco and was curious if someone with expertise could gauge the potential impact of a forthcoming create react app reworked for Webpack 5.

It doesn't seem like the release is impending, but it would be good to have some idea on how much that might change craco, if at all.

Here's [a PR for the webpack 5 in cra](https://github.com/facebook/create-react-app/pull/7929).

**Comment by threepointone** [comment]
This guide would be relevant as and when it does https://webpack.js.org/migrate/5/
This is the main create-react-app issue tracking the changes being made https://github.com/facebook/create-react-app/issues/9994

**Comment by andreibsk** [comment]
Just here to mention that the [WP5 PR got merged](https://github.com/facebook/create-react-app/pull/11201) and a new `5.0.0-next.31` version of react-scripts is [available](https://www.npmjs.com/package/react-scripts/v/5.0.0-next.31).
