### ISSUE TITLE
Add support for NextJS

### ISSUE THREAD

**Issue by DeeeeLAN** [gsoft-inc/craco#204]
Hi, 

Maybe this will already work out of the box. NextJS has their own build scripts, but being react under the hood, I imagine it would be simple to add support, if it doesn't already exist. I didn't see any mention of NextJS yet though.

**Comment by chungweileong94** [comment]
The purpose of this project is not for React, but create-react-app in particular, since CRA is lack customization in many ways. If you compare CRA with NextJS, NextJS already provides tons of customizations.

**Comment by DeeeeLAN** [comment]
Ah, okay that makes sense. It is true that the next.config.js is really awesome, you can override most of what you would need.
