### ISSUE TITLE
Eslint plugin (@typescript-eslint) not working as intended with craco

### ISSUE THREAD

**Issue by NiloDrumond** [gsoft-inc/craco#212]
I started using craco because normal CRA doesn't work with paths aliases anymore, but I've faced a few problems.

1-  I use the plugin @typescript-eslint, but when I run craco start my eslint configs doesn't work as intendend. What do i mean by that? For example, I have disabled the rule "camelcase", but i was getting Failed to Compile because of @typescript-eslint/camelcase, so I had to disable these rules two times, even though vscode and eslint on the terminal doesn't show any errors.

2- When I run craco start, my terminal shows a bunch of warnings, all of them from @typescript-eslint. I want to get warnings from react and other libs on my terminal, but not from eslint.

It seems to me that this problem is related specifically with @typescript-eslint, but I've have been using this plugin for quite some time and using it on my react-native project without problems. Does anyone have any idea what might be causing this problem and how to fix it?

My configs:

### package.json
```{
  "name": "wecheck-web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "craco start",
    "postinstall": "patch-package",
    "build": "craco build",
    "test": "craco test",
    "eject": "react-scripts eject"
  },
  "dependencies": {
    "@craco/craco": "^5.8.0",
    "@firebase/app": "^0.6.13",
    "@firebase/storage": "^0.4.1",
    "@nozbe/watermelondb": "^0.20.0",
    "@nozbe/with-observables": "^1.0.7",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.53",
    "@types/react-dom": "^16.9.8",
    "axios": "^0.21.0",
    "crypto-js": "^4.0.0",
    "device-uuid": "^1.0.4",
    "jwt-decode": "^3.1.1",
    "moment": "^2.29.1",
    "patch-package": "^6.2.2",
    "postinstall-postinstall": "^2.1.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.4",
    "rrule": "^2.6.6",
    "typescript": "^4.0.3",
    "uuid": "^8.3.1",
    "web-vitals": "^0.2.4",
    "yup": "^0.29.3"
  },
  "devDependencies": {
    "@types/crypto-js": "^4.0.1",
    "@types/device-uuid": "^1.0.0",
    "@types/jwt-decode": "^3.1.0",
    "@types/react-router-dom": "^5.1.6",
    "@types/uuid": "^8.3.0",
    "@types/yup": "^0.29.9",
    "@typescript-eslint/eslint-plugin": "^4.7.0",
    "@typescript-eslint/parser": "^4.7.0",
    "eslint": "6.6.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-prettier": "^6.15.0",
    "eslint-import-resolver-typescript": "^2.3.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4",
    "prettier": "^2.1.2"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

### craco.config.js
```const path = require('path');
const { ESLINT_MODES } = require("@craco/craco")
const customESLintConfig = require('./.eslintrc');

module.exports = {
  // Workaround https://github.com/gsoft-inc/craco/issues/187
    eslint: {
      mode: ESLINT_MODES.extends,
      configure: () => customESLintConfig,
    },
    webpack: {
      alias: {
        '@': path.resolve(__dirname, 'src'),
        '@security': path.resolve(__dirname, 'src/modules/security'),
        '@event': path.resolve(__dirname, 'src/modules/event'),
        '@shared': path.resolve(__dirname, 'src/modules/shared'),
        '@calendar': path.resolve(__dirname, 'src/modules/calendar'),
        '@services': path.resolve(__dirname, 'src/services'),
        '@utils': path.resolve(__dirname, 'src/utils'),
        '@screens': path.resolve(__dirname, 'src/screens'),
        '@hooks': path.resolve(__dirname, 'src/hooks'),
        '@components': path.resolve(__dirname, 'src/components')
      },
    }
}
```

### tsconfig.json
```{
  "extends": "./tsconfig.paths.json",
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "strictPropertyInitialization": false,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}
```

**Comment by TC-mSundaram** [comment]
@NiloDrumond I think I was having similar issues and what solved it for me was downgrading to 

```
"@typescript-eslint/eslint-plugin": "4.0.1",
"@typescript-eslint/parser": "4.0.1",
```

which I found here - https://stackoverflow.com/a/63862578

I believe that this is fixed in the latest create-react-app / ESLint, but Craco is not up to date yet.

**Comment by Manny91** [comment]
Hey @TC-mSundaram, @NiloDrumond , just wondering if you did manage to get the rules defined in eslintrc.js when building with craco?

I'm doing 
```
const customESLintConfig = require("../.eslintrc");

module.exports = {
...
   eslint: {
      mode: ESLINT_MODES.extends,
      configure: customESLintConfig,
    },
...
}
```
and doesnt really pick up the rules 😕

**Comment by liao02x** [comment]
Try adding `EXTEND_ESLINT=true` in your env file

**Comment by NiloDrumond** [comment]
@Manny91 

First, is you eslintrc on the parent folder? because your import is "../.eslinrc" not "./.eslinrc".
Second, try setting "configure" like i did ` configure: () => customESLintConfig,`

**Comment by NiloDrumond** [comment]
> @NiloDrumond I think I was having similar issues and what solved it for me was downgrading to
> 
> ```
> "@typescript-eslint/eslint-plugin": "4.0.1",
> "@typescript-eslint/parser": "4.0.1",
> ```
> 
> which I found here - https://stackoverflow.com/a/63862578
> 
> I believe that this is fixed in the latest create-react-app / ESLint, but Cr aco is not up to date yet.

Didn't work :/

**Comment by Manny91** [comment]
@NiloDrumond  yes it is in the parent folder thats why I changed the import route, tried as well leaving the function for the configure and it resulted the same thing, none of those worked for me :/

**Comment by chungweileong94** [comment]
Based on my experience, it's because CRA by default came with a specific version of `@typescript-eslint/eslint-plugin` & `@typescript-eslint/parser`. So if you install a different version, you will notices that the CRA ESLint will fail to pick up any rules regarding the typescript-eslint.

You might want to check the dependencies of `react-script` and see which version it actually uses.
