### ISSUE TITLE
watchOptions lost

### ISSUE THREAD

**Issue by christianbpedersen** [gsoft-inc/craco#214]
Hi!

Using craco start webpack, and trying to get watchOptions - specifically interval and ignored - to get from the craco.config.js webpack session to the actual underlying webpack-dev-server, but the watchOptions (even through it will throw and error if I make a typo to one of the settings, so something IS validating them properly) are not carried through to the Server.js in webpack. 

`module.exports = {
  webpack: {
    configure: {
      watch: true,
      watchOptions: {
        poll: true,
        aggregateTimeout: 200
      }
    }
  },
...`

Is this a known issue?

**Comment by signal-intrusion** [comment]
Agreed.

**Comment by CristianYanez-Zoetis** [comment]
Having the same issue, could this be reopened?

**Comment by brian-murphy** [comment]
Same, could use some attention here. I'm seeing 
```
(node:22235) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument needs to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.
```
