### ISSUE TITLE
Update the postcss to v8 for Tailwindcss 2.x support

### ISSUE THREAD

**Issue by sahilpurav** [gsoft-inc/craco#215]
Tailwindcss requires postcss v8 and craco uses postcss v7.

Upgrading the tailwindcss to 2.x gives the following error:

![image](https://user-images.githubusercontent.com/8158506/100106096-21aaaf80-2e8e-11eb-8d43-fcd3a69ed342.png)

I've the following configuration in:

**postcss.config.js**
```
module.exports = {
  plugins: [
    require('tailwindcss'),
  ],
};
```

**craco.config.js**

```
const { POSTCSS_MODES } = require('@craco/craco');

module.exports = {
  style: {
    postcss: {
      mode: POSTCSS_MODES.file,
    },
  },
};

```

**Comment by sahilpurav** [comment]
Closing this as this has to be done by CRA not craco.

**Comment by seawatts** [comment]
Looks like it just got merged in CRA https://github.com/facebook/create-react-app/pull/10456
