### ISSUE TITLE
How to import antd and antd-mobile in the same cra project ?

### ISSUE THREAD

**Issue by Kilims** [gsoft-inc/craco#217]
How to import antd and antd-mobile in the same cra project ?

any chance that could share the carco.config.js file ?

currently my carco.config.js is looking like this :

```
const CracoLessPlugin = require('craco-less');

module.exports = {
  plugins: [
    {
      plugin: CracoLessPlugin,
      options: {
        lessLoaderOptions: {
          lessOptions: {
            modifyVars: { '@primary-color': '#1DA57A' },
            javascriptEnabled: true,
          },
        },
      },
    },
  ],
};
```

it could work well with antd customized theme with less vars (all go along exactly the same with the official website set up)

**Comment by unzico** [comment]
I've created a [project](https://github.com/unzico/cra4-ts-antd-sass), which uses antd together with cra a long time ago. Not sure, if it still works, but it may help you. It basically just uses [craco-antd](https://github.com/DocSpring/craco-antd) to make things work. Good luck!
