### ISSUE TITLE
Typescript app giving "Cannot find ESLint loader (eslint-loader)" error

### ISSUE THREAD

**Issue by sethreidnz** [gsoft-inc/craco#221]
I have just created a new project you can [find here](https://github.com/sethreidnz/craco-typescript-eslint-issue-repro/tree/master) and I get the following error flash up real quick before going to the usual create-react-app build message.

![image](https://user-images.githubusercontent.com/4713713/101266007-40734500-37b0-11eb-87c7-68c565998f04.png)

The above project all I've done is create a new create react app like:

```
create-react-app my-app --template typescript
```

Then followed the Craco instalation guide. I don't know that it actually affects anything. From what I can tell, eslint is working just fine, but it's a strange error to be getting. Looks like its this code here:

https://github.com/gsoft-inc/craco/blob/9f4077d8f7718158142636d47d39a862d5877df5/packages/craco/lib/features/webpack/eslint.js#L96

So I guess it's not finding that loader? A stab in the dark is that the typescript template is using typescript-eslint?

**Comment by alexasselin008** [comment]
Hi Seth, 

You can read more on this issue here : https://github.com/gsoft-inc/craco/issues/205

Craco doesn't fully support react-scripts 4.0.0 just yet. There is a couple workaround mentionned in the linked issue.

Hope this helps

**Comment by sethreidnz** [comment]
Dang I see. Yeah it seems to work, but then in a CI/CD environment it blows up. I am just going to wait because I'm just playing around with some side projects with this so no stress.

Thanks for the fast response this is a cool tool! I haven't touched create react app in about a year and this makes it so you can actually get everything you want going on, but not have to maintain a webapck build or be boxed in.
