### ISSUE TITLE
CRACO, worker-plugin, and, react-refresh-webpack-plugin

### ISSUE THREAD

**Issue by justrealmilk** [gsoft-inc/craco#225]
I'll start by being honest - I'm not sure which repo this issue truly belongs to but I'll start here.

I use CRACO to achieve a few things, including enabling web workers.

This is my config prior to react-scripts 4. Worked great
```js
const { whenProd, addBeforeLoader, loaderByName } = require("@craco/craco");
const WorkerPlugin = require('worker-plugin');

module.exports = {
  webpack: {
    configure: function(webpackConfig) {
      // some stuff

      return webpackConfig;
    },
    plugins: [
      new WorkerPlugin(),
    ],
  },
};
```

Since updating everything, I've encountered some issues.

![image](https://user-images.githubusercontent.com/156681/101603256-24d88c00-39b4-11eb-921d-4123cec7bfb8.png)

The config I've attempted (and some variations on)
```js
const { whenProd, addBeforeLoader, loaderByName } = require("@craco/craco");
const WorkerPlugin = require('worker-plugin');

module.exports = {
  webpack: {
    configure: function(webpackConfig) {
      // some stuff

      return webpackConfig;
    },
    plugins: [
      new WorkerPlugin({
        globalObject: 'this',
        plugins: [
          'react-refresh-webpack-plugin'
        ]
      }),
    ],
  },
};
```

So this error is obviously to do with `react-refresh-webpack-plugin` and I've tried to work out how to trick it into doing the right thing but no luck.

I found https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/24 but couldn't get anything from it to work

What should I do?

**Comment by unzico** [comment]
Did you upgrade react-scripts to v4? Because create-react-app offers Fast Refresh [out of the box](https://github.com/facebook/create-react-app/releases/tag/v4.0.0) since v4 ([PR](https://github.com/facebook/create-react-app/pull/8582)). Not sure, if this fixes your issue, but you should be able to remove any configuration related to Fast Refresh.

**Comment by justrealmilk** [comment]
> Did you upgrade react-scripts to v4? Because create-react-app offers Fast Refresh [out of the box](https://github.com/facebook/create-react-app/releases/tag/v4.0.0) since v4 ([PR](https://github.com/facebook/create-react-app/pull/8582)). Not sure, if this fixes your issue, but you should be able to remove any configuration related to Fast Refresh.

Of course - CRACO 6 requires react-scripts 4.

**Comment by vanduc1102** [comment]
I am confirmed that @liuliangsir comment works , I am using it in https://github.com/vanduc1102/samples/tree/master/reactjs/cra-solidity-etherjs

**Comment by gormonn** [comment]
@vanduc1102 where is your craco there?

**Comment by justrealmilk** [comment]
I removed my dependency of CRACO and instead took to rewriting react-scripts myself.

**Comment by jrejaud** [comment]
> 

Can you elaborate on your solution please? I've been following the guide at https://blog.johnnyreilly.com/2020/02/21/web-workers-comlink-typescript-and-react, however when my client tries to call the URL where the web worker's file is supposed to live, there's nothing there...
