### ISSUE TITLE
Moving package.json / NODE_MODULES up a level?

### ISSUE THREAD

**Issue by stoplion** [gsoft-inc/craco#227]
Is it possible to move package.json / NODE_MODULES up a level and config craco?

Use case:
have two folders..

`/client`
`/server`

There are a lot of shared deps between the two, so I move package.json / NODE_MODULES up a level to root. 

But getting a..
```
$ craco start
Could not find a required file.
  Name: index.html
  Searched in: /Users/geo/Code/Project1/public
```

**Comment by bobwhitelock** [comment]
My project has a similar directory structure, what I did was have symlinks from the `client` directory to my `node_modules`/`package.json`/`yarn.lock` at the top level:

```bash
ln -s ../node_modules client/node_modules
ln -s ../package.json client/package.json
ln -s ../yarn.lock client/yarn.lock
```

(These can be committed, but you might need to ensure you're not gitignore-ing the `node_modules` symlink to commit this.)

And then rewrite your NPM scripts using `craco` like this:

```json
    "start": "cd client && craco start",
    "build": "cd client && craco build",
```

Everything should then work as expected when run from the top level, as `craco` will have everything it needs within the client directory.
