### ISSUE TITLE
How to remove the html-webpack-plugin

### ISSUE THREAD

**Issue by changhui3067** [gsoft-inc/craco#231]
hello there, i want my project build result is a js entry file instead of a html entry.
it seems that i need to remove the html-webpack-plugin which is added by default, so... is there any way to remove the plugin in craco config?

**Comment by changhui3067** [comment]
i think this pr will resolve my question https://github.com/gsoft-inc/craco/pull/224

**Comment by alexasselin008** [comment]
Hi @changhui3067 , you might want to take a look at the new craco version! https://github.com/gsoft-inc/craco/releases/tag/v6.1.0
