### ISSUE TITLE
Using craco with create-react-app in production on heroku fails

### ISSUE THREAD

**Issue by v12golfcart** [gsoft-inc/craco#233]
Context:
+ I'm newer to Craco, so apologies if any of these are dumb questions!
+ I've been using TailwindCSS and followed their instructions precisely on setup, located here [https://tailwindcss.com/docs/guides/create-react-app](url)
+ I'm trying to deploy a simple static website powered by React via Heroku using Craco+Tailwind

**Issue**: Both dev and production builds work locally, but the moment I deploy to heroku, it fails. I get this error when visiting the app:
![Screen Shot 2021-01-10 at 2 59 16 PM](https://user-images.githubusercontent.com/28909758/104137974-b5a8db80-5355-11eb-9ffe-74f71437eb86.png)

And my logs look like this:
![Screen Shot 2021-01-10 at 3 07 58 PM](https://user-images.githubusercontent.com/28909758/104137975-ba6d8f80-5355-11eb-8052-94f95e6e079f.png)

And my craco config (per Tailwind docs) looks like this:
`
module.exports = {
  style: {
    postcss: {
      plugins: [require("tailwindcss"), require("autoprefixer")],
    },
  },
};
`

**Potential cause**: It looks like Heroku is launching a dev build in production. Some notes:
+ Heroku logs indicate "starting a development server"
+ the error on the app suggests the React Refresh exists when it shouldn't in a production environment
+ switching the scripts from craco back to react-scripts resolves production environment issues, and app works again
+ In this thread, one of the comments is about Craco hiding some build scripts but tbh I have no idea if relevant here [https://github.com/DocSpring/craco-less/issues/10](url)

Steps to repro
+ create a brand new react project using npx create-react-app test
+ add tailwind following the instructions precisely
+ deploy all the boilerplate to heroku

Expected behavior: just works as it does locally
Actual behavior: builds succeed, but app crashes due to above errors

**Question**: Is this something I need to fix via craco's config file? I can't seem to figure it out with the documentation and would really appreciate some help.

**Comment by v12golfcart** [comment]
https://medium.com/jeremy-gottfrieds-tech-blog/tutorial-how-to-deploy-a-production-react-app-to-heroku-c4831dfcfa08

NVM, basically fixed it via this.  This was more a heroku problem of serving the dev app instead of build.

**Comment by corgimaman** [comment]
I'm trying to deploy a react app with heroku and tailwind as well - getting issues with craco I believe. How did you get it figured out? https://github.com/corgimaman/Scissors-Palace/ Mine has a front and backend.
