### ISSUE TITLE
Craco command silently fails on start

### ISSUE THREAD

**Issue by jlpanetta1681** [gsoft-inc/craco#241]
Inherited a project that uses Craco as a bridge for use with less files
installed the node_modules and reinstalled them removing the lock file multiple times
on start — craco just doesn’t want to run.
screen shot included of the terminal after running npm start 

@Ryan Hamblin can provide additional help or info as well

![Screenshot (126)](https://user-images.githubusercontent.com/66652502/106062186-72c06500-60c4-11eb-84fb-17a938c85139.png)

**Comment by patricklafrance** [comment]
You can try starting craco with `--verbose`.

https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#debugging

**Comment by jlpanetta1681** [comment]
Thank you much for being available to lend an idea.. started with verbose nd no change. still no error, n browser, nothing..
