### ISSUE TITLE
Error when running yarn start 

### ISSUE THREAD

**Issue by Tvlasev** [gsoft-inc/craco#251]
I'm getting an error when I run yarn start - UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''

Hare is my package.json file: 

![image](https://user-images.githubusercontent.com/40581749/107862811-1dbc7700-6e58-11eb-83a5-7e566d03fac1.png)

**Comment by InnovativeCoder** [comment]
Same, with npm start. Moved back to 6.0.0 and now it works fine.

**Comment by Tvlasev** [comment]
Yes, I have tried that but no results.

1. I removed the carco - yarn remove @craco/craco 
2. Added 6.0.0 verison - yarn add @craco/craco@6.0.0 

I have tried with 5.9.0 and 5.8.0, even I removed node_modules folder and the yarn.lock file, run yarn install, but I got the same error upon start

**Comment by yomybaby** [comment]
Don't forget to make `craco.config.js` file. 😉

**Comment by Tvlasev** [comment]
> Don't forget to make `craco.config.js` file. 😉

yep... I did create a file but it wasn't in the root directory, but in the src folder. I moved it and it works, thanks : )

**Comment by kintz09** [comment]
> > Don't forget to make `craco.config.js` file. 😉
> 
> yep... I did create a file but it wasn't in the root directory, but in the src folder. I moved it and it works, thanks : )

I had this same issue. Didn't even notice I added it to the src folder by accident. Thanks for the info!
