### ISSUE TITLE
Craco not working after update

### ISSUE THREAD

**Issue by TrofinSorin** [gsoft-inc/craco#255]
![image](https://user-images.githubusercontent.com/43543139/109199579-4aea1d00-77a8-11eb-8809-9ca6bab742b8.png)

"@craco/craco": "^6.1.1",
"craco-alias": "^2.1.1",
"cross-env": "^7.0.3",
 "react-scripts": "^3.4.4",
 "react": "^17.0.0",
 "react-dom": "^17.0.0",

@craco/craco": "^5.6.4", It works with this version but.. i want all latest updates to work.

I tried even upgrading to react scripts 4.0.0.

**Comment by patricklafrance** [comment]
We don't support react-scripts 3* anymore.

I don't know how you upgraded to react-script 4.0.0 but we read CRA version from react-script package.json file and throw an error if it's lower than 4.

If you still have the error, my guess is there is a problem with your installation.
