### ISSUE TITLE
craco ssl ciphers and secureoptions not workign in  craco.config.js file1

### ISSUE THREAD

**Issue by learnpardha** [gsoft-inc/craco#260]
Hi all,

I have enabled https on my devserver it is working fine but recently our security team asked to add secureoptions and disable weak ciphers . The below mentioned configuration is not working. 

Please advise how can i set secureOptions , ciphers inside devserver in craco.config file

Is that possible? if yes please let me know. Pardon my ignorance
 module.exports = {
  devServer: {

    https: true,
    key: fs.readFileSync('ssl/dcap-np.trusted.visa.com.key'),
    cert: fs.readFileSync('ssl/latest.crt'),
    port: 8443,
    //ca: fs.readFileSync('/path/to/ca.pem'),
    disableHostCheck: true
     secureOptions: require('constants').SSL_OP_NO_SSLv3 | require('constants').SSL_OP_NO_TLSv1 
 ciphers: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305-SHA256:ECDHE-RSA-CHACHA20-POLY1305-SHA256:ECDHE-ECDSA-AES256-CBC-SHA384:ECDHE-RSA-AES256-CBC-SHA384:ECDHE-ECDSA-AES256-CBC-SHA256:ECDHE-RSA-AES256-CBC-SHA256:ECDHE-ECDSA-AES128-CBC-SHA256:ECDHE-RSA-AES128-CBC-SHA256:ECDH-ECDSA-AES128-CBC-SHA256:ECDH-ECDSA-AES256-CBC-SHA384:ECDH-RSA-AES128-CBC-SHA256:ECDH-RSA-AES256-CBC-SHA384:ECDH-ECDSA-AES128-GCM-SHA256:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-RSA-AES128-GCM-SHA256:ECDH-RSA-AES256-GCM-SHA384:RSA-AES128-GCM-SHA256:RSA-AES256-GCM-SHA256:RSA-AES128-CBC-SHA256:RSA-AES256-CBC-SHA384:!aNULL:!eNULL:!NULL:!3DES:!RC4:!RC2',

  },

**Comment by webdeveric** [comment]
Your configuration of `https` is wrong. Try this (untested).

```js
module.exports = {
    devServer: {
        port: 8443,
        disableHostCheck: true,
        https: {
            key: fs.readFileSync('ssl/dcap-np.trusted.visa.com.key'),
            cert: fs.readFileSync('ssl/latest.crt'),
            //ca: fs.readFileSync('/path/to/ca.pem'),
            secureOptions: require('constants').SSL_OP_NO_SSLv3 | require('constants').SSL_OP_NO_TLSv1,
        },
    }
};
```
