### ISSUE TITLE
Default ESLint config example

### ISSUE THREAD

**Issue by justrealmilk** [gsoft-inc/craco#261]
I'd super benefit from a solid example of an ESLint config - I'm sure I'm not alone as ESLint is hard at the best of times.

I'm currently using...
```
  eslint: {
    configure: {
      parser: '@typescript-eslint/parser',
      plugins: ['@typescript-eslint'],
      extends: [
        'react-app',
      ],
      rules: {
        'import/no-anonymous-default-export': 'off',
        'jsx-a11y/anchor-has-content': 'off',
        'jsx-a11y/anchor-is-valid': 'off',
        'no-unused-vars': 'off',
        'no-use-before-define': 'off',
        'react-hooks/exhaustive-deps': 'off',
        '@typescript-eslint/no-inferrable-types': 'warn',
        '@typescript-eslint/no-unused-vars': 'off',
      },
    },
  },
```
And it appears to deactivate like... All rules... And I've just been working like this for weeks now because I gave up jumping through hoops! 😂

**Comment by patricklafrance** [comment]
Of course, is this something you could submit a PR for? It could be a new [recipe](https://github.com/gsoft-inc/craco/tree/master/recipes), something like "extend-eslint-config".

**Comment by nick4fake** [comment]
@patricklafrance please reread his question, it literally states that he doesn't know how to do it correctly.

I basically have the same question as documentation examples don't work.
