### ISSUE TITLE
css-loader exportLocalsConvention (formerly localsConvention) not working in CRACO config. Wanting to convert kebab to camelCase

### ISSUE THREAD

**Issue by kintz09** [gsoft-inc/craco#266]
I'm trying to implement the [set-css-loader-locals-convention](https://github.com/gsoft-inc/craco/blob/master/recipes/set-css-loader-locals-convention/craco.config.js) recipe and I'm getting an error hoping someone can guide me to fix.

Implementing the recipe as shown here:
```js
module.exports = {
  style: {
    css: {
      loaderOptions: {
        localsConvention: "camelCase",
      }
    },
  }
}
```
produces the following compiler error:
```bash
Failed to compile.

./src/Player/App/containers/WorkbenchWrapper/WorkbenchWrapper.module.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-7-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-7-4!./src/Player/App/containers/WorkbenchWrapper/WorkbenchWrapper.module.scss)
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'localsConvention'. These properties are valid:
   object { url?, import?, modules?, icss?, sourceMap?, importLoaders?, esModule? }
```
<img width="828" alt="image" src="https://user-images.githubusercontent.com/10118752/111709084-3972be80-8804-11eb-84b7-ace6148de165.png">

I believe this is broken starting in CRA4. Create React App v4 uses css-loader version 4.3.0 and a quick look at the documentation for [css-loader@4.3.0](https://github.com/webpack-contrib/css-loader/tree/v4.3.0) informed me that the property name has changed to [exportLocalsConvention](https://github.com/webpack-contrib/css-loader/tree/v4.3.0#exportlocalsconvention).

First thing I tried was to simply update the property name using the same recipe:
```js
module.exports = {
  style: {
    css: {
      loaderOptions: {
        exportLocalsConvention: "camelCase",
      }
    },
  }
}
```
This resulted in the exact same error as above. This does make sense considering the error informs us which properties are valid. 

The webpack docs show this property being applied to under modules, so I also tried this config:
```js
module.exports = {
  style: {
    css: {
      modules: {
        options: {
          exportLocalsConvention: "camelCase"
        }
      }
    },
  }
}
```
I don't get any errors with this config, but it also doesn't convert my css/scss classes from kebab to camelCase. My classes are still coming back as undefined.

Just for clarity, I'm trying to set up a new CRA project for sass modules where the typescript-plugin-css-modules plugin handles converting css class names from kebab to camel case for intelliJ and where the css-loader converts the final css class names from kebab to camel case.

Could anyone with more experience with CRACO and css-loader help me figure out the proper configuration?

**Comment by kintz09** [comment]
I have a different project configuration now than when I created this issue, but I think this is how the CRACO config file would need to look to support the `localsConvention` parameter in a CRA v4 project:

```js
module.exports = {
  style: {
    css: {
      loaderOptions: {
        modules: {
            localsConvention: "camelCase"
        }
      }
    }
  }
}

**Comment by AnGonch7557** [comment]
CamelCase will working if you write as I has wrote below:

`module.exports = {
    style: {
        modules: {
            localIdentName: "[local]_[hash:base64:5]",
        },
        css: {
            loaderOptions: {
                modules: {
                    exportLocalsConvention: "camelCaseOnly",
                }
            }
        }
    }
};`

But I have other problem - modules work perfectly, but other css and scss styles were broken.

So I had before adding "exportLocalsConvention":
![image](https://user-images.githubusercontent.com/81772228/119744406-a35ab480-be94-11eb-83c7-171508e3056c.png)


and I have now:
![image](https://user-images.githubusercontent.com/81772228/119744541-e9177d00-be94-11eb-82a8-76d02d38b7bc.png)


I changed only .cracorc file.

**Comment by chuckmasucci** [comment]
This is a late response, but I will leave it in case anyone else is looking for the answer like I was. To make the css-loader work correctly, you need to add `auto: true` to the modules object.

```
  style: {
    css: {
      loaderOptions: {
        modules: {
          auto: true,
          exportLocalsConvention: 'camelCaseOnly',
        },
      },
    },
  },
```
