### ISSUE TITLE
TypeError: Cannot assign to read only property 'paths' of object

### ISSUE THREAD

**Issue by yordis** [gsoft-inc/craco#270]
Hey folks, by any chance do you know how to fix this? I would like to setup an alias, but the issue is that my `tsconfig.json` can't set the aliases, so I am wondering if there is a workaround for the issue

```text
❯ yarn test
yarn run v1.22.10
$ craco test
/myapp/node_modules/react-scripts/scripts/test.js:20
  throw err;
  ^

TypeError: Cannot assign to read only property 'paths' of object '#<Object>'
    at verifyTypeScriptSetup (/myapp/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239:43)
```

```text
The following changes are being made to your tsconfig.json file:
  - compilerOptions.paths must not be set (aliased imports are not supported)
```

### Setup

```jsonc
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]  // this is the problem
    }
  }
}

```

```js
const path = require('path');

module.exports = {
  style: {
    postcss: {
      plugins: [require('tailwindcss'), require('autoprefixer')],
    },
  },
  webpack: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  jest: {
    configure: (jestConfig) => {
      jestConfig.moduleNameMapper['^@/(.*)$'] = '<rootDir>/src/$1';
      return jestConfig;
    },
  },
};
```

**Comment by yaojin2070** [comment]
I have the same problem. Have you solved it， I tried to solve it this way，But it doesn't work
![image](https://user-images.githubusercontent.com/48686959/113513004-05d0bc00-959a-11eb-88ae-37b351fc7e52.png)

**Comment by yordis** [comment]
@yaojin2070 I haven't solved the issue sadly, please if you find any workaround share it here 🙏🏻

**Comment by yaojin2070** [comment]
> @yaojin2070 I haven't solved the issue sadly, please if you find any workaround share it here 🙏🏻 

    I think your path configuration is set in tsconfig.json, and then the path configuration will disappear when you start the project, right?


 You need to put your path configuration in a separate file, and then extends this file in config.json, just like I did in the image above. I couldn't solve this before because I didn't put a * after the path

**Comment by yordis** [comment]
Pump
