### ISSUE TITLE
Use --selectProjects option with Jest

### ISSUE THREAD

**Issue by mstelz** [gsoft-inc/craco#272]
Using Craco I am attempting to utilize the Jest's [selectProjects](https://jestjs.io/docs/cli#--selectprojects-project1--projectn) cli option to invoke a specific defined project within the configuration. 

Using this as the _craco.config.js_
```javascript
module.exports = {
  jest: {
    configure: {
      projects: [
        {
          name: "unit",
          displayName: "unit",
          testMatch: ["<rootDir>/**/*.test.*"],
        },
        {
          name: "playwright",
          displayName: "playwright",
          testMatch: ["<rootDir>/**/*.uitest.*"],
        },
      ],
      globals: {
        CONFIG: true,
      },
    },
  },
};
```

And then in my _package.json_ I am defining the following scripts:
```json
{
  ...
    "test": "craco test --watchAll=false --coverage --json --selectProjects unit",
    "test:ui": "craco test --watchAll=false --coverage --json --selectProjects playwright --showConfig"
  ...
}
```

But it appears it cannot find a configuration as it throws the following error:
> Error: Jest: Cannot use configuration as an object without a file path.
    at readConfig (/Users/mstelze/Git/react-example/node_modules/jest-config/build/index.js:188:13)
    at /Users/mstelze/Git/react-example/node_modules/jest-config/build/index.js:447:18
    at Array.map (<anonymous>)
    at readConfigs (/Users/mstelze/Git/react-example/node_modules/jest-config/build/index.js:441:10)
    at async runCLI (/Users/mstelze/Git/react-example/node_modules/@jest/core/build/cli/index.js:230:59)
    at async Object.run (/Users/mstelze/Git/react-example/node_modules/jest-cli/build/cli/index.js:163:37)

Any thoughts? Am I missing something in the configuration or is this function not supported?

**Comment by bluSCALE4** [comment]
Any thoughts on this?
