### ISSUE TITLE
devServer config functional is not work

### ISSUE THREAD

**Issue by calvinsnax** [gsoft-inc/craco#274]
```js
#craco.config.js
module.exports = ({ env }) => {
  return {
    devServer: (
      devServerConfig,
      { env, paths, proxy, allowedHost },
    ) => {
      devServerConfig.port = 4000;
      devServerConfig.contentBasePublicPath = paths.publicUrlOrPath;
      return devServerConfig;
    },
  };
};
```

How can I do? is it bug?

**Comment by pomelott** [comment]
> ```js
> #craco.config.js
> module.exports = ({ env }) => {
>   return {
>     devServer: (
>       devServerConfig,
>       { env, paths, proxy, allowedHost },
>     ) => {
>       devServerConfig.port = 4000;
>       devServerConfig.contentBasePublicPath = paths.publicUrlOrPath;
>       return devServerConfig;
>     },
>   };
> };
> ```
> 
> How can I do? is it bug?



> ```js
> #craco.config.js
> module.exports = ({ env }) => {
>   return {
>     devServer: (
>       devServerConfig,
>       { env, paths, proxy, allowedHost },
>     ) => {
>       devServerConfig.port = 4000;
>       devServerConfig.contentBasePublicPath = paths.publicUrlOrPath;
>       return devServerConfig;
>     },
>   };
> };
> ```
> 
> How can I do? is it bug?

craco.config.js don't support this, configed passively in creat-react-app. you can change it in .env、.env.development and so on. for detail, view [https://create-react-app.dev/docs/advanced-configuration](https://create-react-app.dev/docs/advanced-configuration)

**Comment by pomelott** [comment]
> ```js
> #craco.config.js
> module.exports = ({ env }) => {
>   return {
>     devServer: (
>       devServerConfig,
>       { env, paths, proxy, allowedHost },
>     ) => {
>       devServerConfig.port = 4000;
>       devServerConfig.contentBasePublicPath = paths.publicUrlOrPath;
>       return devServerConfig;
>     },
>   };
> };
> ```
> 
> How can I do? is it bug?

craco.config.js don't support this, configed passively in creat-react-app. you can change it in .env、.env.development and so on. for detail, view [https://create-react-app.dev/docs/advanced-configuration](https://create-react-app.dev/docs/advanced-configuration)
