### ISSUE TITLE
Not working well with HtmlWebpackPlugin - wrong output

### ISSUE THREAD

**Issue by theunreal** [gsoft-inc/craco#279]
## Current behaviour 💣
The module generated the wrong output file

## Expected behaviour ☀️
the index I provided in the `template`  config field along with the webpack output
### Reproduction Example 👾

Create react app + craco
craco.config.js
```
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = () => {
    return {
        webpack: {
            plugins: [
                new HtmlWebpackPlugin({
                    hash: false,
                    template: './index.php',
                    filename: 'index.php',
                }),
            ],
        },
    };
};

The output is (index.php):
`<head><link href="/components/static/css/main.6dea0f05.chunk.css" rel="stylesheet"></head>/components/static/media/index.e8e919fb.php<script src="/components/static/js/runtime-main.3c932baa.js"></script><script src="/components/static/js/2.521c8692.chunk.js"></script><script src="/components/static/js/main.856a5df0.chunk.js"></script>`

my index.php is a lot different... it has 5k lines of code, and it has a strange line in it:
`/components/static/media/index.e8e919fb.php`
```

## Environment 🖥

+-- html-webpack-plugin@4.5.2
`-- react-scripts@4.0.3
  `-- html-webpack-plugin@4.5.0

`-- react-scripts@4.0.3
  `-- webpack@4.44.2

**Comment by DanielRuf** [comment]
You may have to remove the existing plugin and add it again and use `index.html` as `filename` setting:

![image](https://user-images.githubusercontent.com/827205/130041662-c7724a89-8a75-449d-8ef8-37e942b14e88.png)

![image](https://user-images.githubusercontent.com/827205/130041691-f6056cc5-6c7d-4c8a-971f-2c4ce733398b.png)

You can easily check the current plugin configurations:
![image](https://user-images.githubusercontent.com/827205/130042689-a7089a50-2bc1-4c5d-8b58-8b49c6476b9e.png)

![image](https://user-images.githubusercontent.com/827205/130043133-8ed87cef-2e22-443e-88fd-16e4fdefa2e8.png)

Working setup on my side:
![image](https://user-images.githubusercontent.com/827205/130043638-565dd0d4-502e-430c-9ba0-8b36f8ae9a6b.png)
