### ISSUE TITLE
craco:  *** Cannot find ESLint plugin (ESLintWebpackPlugin). ***

### ISSUE THREAD

**Issue by yuri-sakharov** [gsoft-inc/craco#281]
Hi, 

I'm using create-react-app and getting this message on:
```
> DISABLE_ESLINT_PLUGIN=true craco start

craco:  *** Cannot find ESLint plugin (ESLintWebpackPlugin). ***
```
when run without `DISABLE_ESLINT_PLUGIN=true ` only `craco start` it started without the message.
How not to get the message with `DISABLE_ESLINT_PLUGIN=true ` ?

**Comment by zhuhang-jasper** [comment]
This works for me: https://www.npmjs.com/package/craco-eslint-webpack-plugin

**Comment by zhuhang-jasper** [comment]
I think if u disable eslint in craco, then you don't need to use `DISABLE_ESLINT_PLUGIN=true` anymore? 

In `craco.config.js`, add this:
```
module.exports = {
  // ...
  eslint: {
    enable: false
  },
  // ...
}
```

**Comment by kalideir** [comment]
`I replaced postcss with postOptions in carco.config.js and it's working !`

**Comment by Nate97320** [comment]
i had same issue 
and followed the suggestions:
"I replaced postcss with postOptions in carco.config.js and it's working "

**Comment by woss** [comment]
hi, 

i'm still getting this issue with the eslint disabled like this:
docs says it should be done like that https://craco.js.org/docs/configuration/eslint/#eslintenable 

<img width="449" alt="image" src="https://github.com/dilanx/craco/assets/80440/45ec1196-4f3b-4dca-abf1-f63f9be1ba8a">

```js
module.exports = {
  // ...
  eslint: {
    enable: false
  },
  // ...
}
```
