### ISSUE TITLE
支持antd4.x 版本css样式文件按需加载babel-plugin-import

### ISSUE THREAD

**Issue by JieleeJie** [gsoft-inc/craco#291]
React中使用antd 4.x后在网上没搜到CSS按需加载的教程，自己摸索了一番，踩了一些坑，简单记录一下。

- 在antd 4.x后，使用 `craco `对 create-react-app 进行自定义配置。 `craco `的[相关配置看官网](https://ant.design/docs/react/use-with-create-react-app-cn#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE)

- 使用`babel-plugin-import`， `babel-plugin-import`是一个用于按需加载组件代码和样式的 babel 插件
    1. 安装：`$ yarn add babel-plugin-import`
    2. 配置：在`craco.config.js`中配置如下：
        ```
        module.exports = {
                    babel: {
                        plugins: [['import', {
                            libraryName: 'antd',
                            libraryDirectory: 'es',
                            style: 'css',
                        }]],
                    },
                };
       ```

- 踩坑：
    不要使用`.babelrc`文件，[原因看这](https://blog.csdn.net/weixin_39536427/article/details/111624122)
    曾尝试引入craco社区维护的相关插件来解决`.babelrc`问题，最终以失败告终
    
![image](https://user-images.githubusercontent.com/50036357/118211556-e1bca080-b49e-11eb-9bde-384a07610f27.png)

- 还是多看官方的配置文档有用。
    [babel-plugin-import](https://github.com/ant-design/babel-plugin-import)
    [craco](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#configuration)

**Comment by igorsantos07** [comment]
Are you sure you expect help with a Chinese issue in an English-based repo?
