### ISSUE TITLE
what is the proper way to register multiple craco plugins ?

### ISSUE THREAD

**Issue by garyng2000** [gsoft-inc/craco#292]
The 'doc's is not very clear and most of the example only show 'one'.

plugins: [ { plugin: craco-foo-plugin }]

do i do it like this ?

plugins: [ { plugin: craco-foo-plugin }, {plugin: craco-bar-plugin }]

**Comment by patricklafrance** [comment]
Yes it is the correct syntax.

**Comment by garyng2000** [comment]
I tried this syntax but get an error saying rules.some is not a function.
