### ISSUE TITLE
Eslint Config Extend

### ISSUE THREAD

**Issue by LuisValgoi** [gsoft-inc/craco#295]
How to add this into `craco.config.js`? 

```js
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
```

**Comment by marcofugaro** [comment]
You can add this directly to package.json: https://create-react-app.dev/docs/setting-up-your-editor/#extending-or-replacing-the-default-eslint-config

However, when craco is involved, it needs a couple of dependencies as well.

**Comment by nick4fake** [comment]
@marcofugaro that's literally the question "how to do it with Craco".

I have the same issue, nothing from the docs or other issues works for me, it simply ignores package.json config.

**Comment by marcofugaro** [comment]
Oh right, the craco scripts probably ignore the package.json then...
