### ISSUE TITLE
using cdn externals with craco cra

### ISSUE THREAD

**Issue by velociwabbit** [gsoft-inc/craco#299]
CRA has no native support for using CDN versions of React, react-dom,  react-router-dom, history, etc.

Without these repos I can reduce my bundle to very small indeed. 

There is no example of how to do this with Craco.  

Is it even possible? I know that CRA does a great deal of tree pruning ... I am wondering whether it is even worth the trouble.

If it is possible but no one has tried to do it please let me know and I will be the canary in the coal mine (so to speak).

**Comment by flyingCrp** [comment]
like this :
```
module.exports = {  
    webpack: {
        configure: (webpackConfig) => {
            webpackConfig.externals = {
                react: 'React',
                'react-dom': 'ReactDOM',
            };
            return webpackConfig;
        },
    },
};

```
