### ISSUE TITLE
How to resolve the error - sh: 1: craco: Permission denied

### ISSUE THREAD

**Issue by vaibhavpandeyprayag** [gsoft-inc/craco#308]
I set up a react app on Windows platform ((react app + typescript) + craco + tailwindcss). Then I copied the app folder on Ubuntu platform (which contains vscode, node, npm). When I run "npm start" command on vscode terminal, the error **sh: 1: craco: Permission denied** shows up.
I want to know what the problem is, and how to resolve it?
Please help.

**Comment by azula9713** [comment]
Same issue. But this works fine on my SSD, which runs the OS. But I have a secondary hard drive in the system. I get this issue when I try to run a project in the secondary hard drive.

**Comment by vaibhavpandeyprayag** [comment]
> I set up a react app on Windows platform ((react app + typescript) + craco + tailwindcss). Then I copied the app folder on Ubuntu platform (which contains vscode, node, npm). When I run "npm start" command on vscode terminal, the error **sh: 1: craco: Permission denied** shows up.
> I want to know what the problem is, and how to resolve it?
> Please help.

Same is the case when a raect-app set on Ubuntu is copied to Windows platform. Does anyone have some explanation?

**Comment by Dakkers** [comment]
have you tried completely removing the `node_modules` folder and reinstalling?

**Comment by vaibhavpandeyprayag** [comment]
Yes. I tried it just now, deleted `node_modules` folder, and ran command `npm start`. Then everything works fine.

**Comment by masudmollah10** [comment]
Error: Command "npm run build" exited with 126

**Comment by Aryaman3007** [comment]
Did your issue got solved , I am also getting same error while vercel deployment.

**Comment by Harshal-Solanki** [comment]
> Did your issue got solved , I am also getting same error while vercel deployment.

I am facing same issue. How to resolve it?

**Comment by g3ntil** [comment]
Hey its been a whole year, did y'all find solution for this error when deploying on vercel?
