### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by programmerWhite** [gsoft-inc/craco#311]
![image](https://user-images.githubusercontent.com/17827176/127252934-ca025915-eaf1-4a97-a5ee-599eca7fff20.png)

**Comment by StevenVerbiest** [comment]
I'm having the same issue. While compiling, at some times, memory usage jumps up. 
If I inspect it, it returns 300mb+ of this gibberish.

![memory](https://user-images.githubusercontent.com/2128348/128482941-516b40cf-1e99-4582-ac3c-b23db74a09ea.png)

Could the problem be the vast amount of assets in the project. Not only images, but also audio files, etc..

**Comment by Mii1128** [comment]
I found a pattern for my project at least. Whenever my IDE throws in an import from 'typescript' it causes a crash with heap out of memory. Since i don't use typescript i can usually just remove these unused imports to get it running again.

**Comment by sumicet** [comment]
Got the same issue

**Comment by mirandajignacio** [comment]
Got the same issue D:
