### ISSUE TITLE
Overriding the options of a Webpack plugin (i.e. `ts-loader`)

### ISSUE THREAD

**Issue by LoganDark** [gsoft-inc/craco#312]
I'm trying to extend the `options` field of a Webpack plugin that CRA already contains (`ts-loader`). I'm trying to do this so I can switch to `ttypescript` and use `typescript-is`. AFAICT the only way to do this is to either remove the plugin and add another with the desired modifications, or use a craco plugin to manually modify the webpack config? How should I go about this?

To use ttypescript, all I have to do is add `compiler: 'ttypescript'` to the ts-loader options. See: https://github.com/harrysolovay/rescripts/issues/41

**Comment by LoganDark** [comment]
Would be a shame if this isn't possible with craco - still bumping into problems that could be solved by this. :(

**Comment by LoganDark** [comment]
Shut up stale bot, you're so useless and annoying

**Comment by dilanx** [comment]
Poor stale bot :pleading_face: oh well I got rid of it I don't like it lol.

Anyway, the `configure` property in the webpack section of the craco config should allow you to do this. I haven't tested this but you could try it out. I referenced [the sample craco config](https://github.com/gsoft-inc/craco/tree/master/packages/craco#configuration-file), [the webpack config docs](https://webpack.js.org/configuration/), and [the issue you linked](https://github.com/harrysolovay/rescripts/issues/41). Please let me know whether or not this works.

```js
/* craco.config.js */
module.exports = {
    webpack: {
        configure: (config) => {
            config.module.rules.unshift({
                test: /\.(ts|tsx)$/,
                use: [
                    {
                        loader: 'ts-loader',
                        options: {
                            compiler: 'ttypescript'
                        }
                    }
                ]
            })
            return config;
        }
    }
}
```

**Comment by LoganDark** [comment]
> Poor stale bot 🥺 oh well I got rid of it I don't like it lol.
> 
> Anyway, the `configure` property in the webpack section of the craco config should allow you to do this. I haven't tested this but you could try it out. I referenced [the sample craco config](https://github.com/gsoft-inc/craco/tree/master/packages/craco#configuration-file), [the webpack config docs](https://webpack.js.org/configuration/), and [the issue you linked](https://github.com/harrysolovay/rescripts/issues/41). Please let me know whether or not this works @LoganDark.
> 
> ```js
> /* craco.config.js */
> module.exports = {
>     webpack: {
>         configure: (config) => {
>             config.module.rules.unshift({
>                 test: /\.(ts|tsx)$/,
>                 use: [
>                     {
>                         loader: 'ts-loader',
>                         options: {
>                             compiler: 'ttypescript'
>                         }
>                     }
>                 ]
>             })
>             return config;
>         }
>     }
> }
> ```

It's been almost a year and I'm actually no longer employed to work on that project, so I can't test your solution. But thank you anyway!
