### ISSUE TITLE
use-ts-loader recipe - "export 'ReactComponent' was not found in..

### ISSUE THREAD

**Issue by KevinDenys** [gsoft-inc/craco#320]
Hi,

We are using the ts-loader recipe found here https://github.com/gsoft-inc/craco/blob/master/recipes/use-ts-loader/craco.config.js

But when we want to export our svgs as an ReactComponent 

`export { ReactComponent as LogoIconSmall } from './logo_small.svg';`

we get the following error message
```
Failed to compile.

./src/assets/icons/index.tsx
"export 'ReactComponent' (reexported as 'LogoIconSmall') was not found in './logo_small.svg'
```

How can we support this?

Thanks!

**Comment by ElattarECC** [comment]
I have the same problem and tried to add

- [SVGR loader](https://react-svgr.com/docs/webpack/) config to craco config file, but it didn't work for me as well .
- [react-svg-loader](https://github.com/boopathi/react-svg-loader) to the craco config file, but didn't work for me as well. 

The only way that worked for me(using [react-svg-loader](https://github.com/boopathi/react-svg-loader))  however i don't like it 
`export  LogoIconSmall from '-!react-svg-loader!./logo_small.svg';`

keep in mind that `-!` allows it to bypass the existing loaders , and I don't know how to bypass the existing loaders using craco config
