### ISSUE TITLE
carco: command not found

### ISSUE THREAD

**Issue by mhraihan** [gsoft-inc/craco#323]
The  "@craco/craco": "^6.1.2", is installed
and update the start script : "start": "craco start",

but, when npm run start,
it does not work.

it said, craco: command not found

what is the solution?
thank you

**Comment by alur222** [comment]
`npm install -g @craco/craco`

**Comment by jaysoo** [comment]
Make sure you have the latest version of `@nrwl/cli` installed  globally.

```
npm install -g @nrwl/cli@latest
```

Or you can prefix with `npx` like:

```
npx nx serve myapp
```

Which will use the local Nx (which is latest).

**Comment by lithammer** [comment]
Not sure what your issue was/is. But I had a similar problem and it was related to the fact I was running `npm install` with `NODE_ENV=production` which meant that no dev dependencies were installed.

**Comment by azielstyle** [comment]
> `npm install -g @craco/craco`

that worked for me, thank you!

**Comment by yairEO** [comment]
Should work without installing globally. That is not a solution.

**Comment by dilanx** [comment]
I agree with @yairEO. Installing globally shouldn't be necessary if craco is installed correctly within the npm project.

After creating a project with `npx create-react-app <app-name>`, you should make sure your working directory is set to your project (`cd <app-name>`), and then all you should need to do is `npm i @craco/craco`.

**Comment by S-Selim** [comment]
npm install -g @craco/craco
