### ISSUE TITLE
Any way to disable file sizes reporter?

### ISSUE THREAD

**Issue by FezVrasta** [gsoft-inc/craco#331]
Hi, the file sizes reporter ran at the end of `build` is very slow, is there any way to disable it with Craco?

I see the logic is embedded in the build script so there's not a specific plugin I can disable.

**Comment by patricklafrance** [comment]
Hi @FezVrasta 

Since it's in the build script file of CRA, there isn't much CRACO can do about it. I suggest you open an issue in the CRA repo.

Thank you
