### ISSUE TITLE
对create-react-app进行自定义配置时一直报错。

### ISSUE THREAD

**Issue by chentle** [gsoft-inc/craco#358]
Can't find file-loader in the development webpack config!
![image](https://user-images.githubusercontent.com/71593936/147046204-49ed1360-08ae-403c-8f06-da14ac017c67.png)
看提示以为是craco-less和@craco/craco版本不适配，我更改二者的版本尝试了几次仍然没有解决问题
依赖如下
![image](https://user-images.githubusercontent.com/71593936/147046548-66525d32-b43a-4629-ada4-c213b4fa7a96.png)

**Comment by chentle** [comment]
我看到有一个人是相同的问题，但是他从npm改用yarn指令重更新之后就欧克了，但我一直用的就是yarn

**Comment by chentle** [comment]
> 我看到有一个人是相同的问题，但是他从npm改用yarn指令重更新之后就欧克了，但我一直用的就是yarn

and I retried with npm commands,failed

**Comment by ZhangWenNbPlus** [comment]
delete package-lock.json and try again

**Comment by caijf** [comment]
craco-less upgrade to v2.0.0 
ref: https://github.com/DocSpring/craco-less/issues/86

or

react-scripts below v4.0.3
