### ISSUE TITLE
craco How to remove css-map?

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [gsoft-inc/craco#359]
![image](https://user-images.githubusercontent.com/17617821/147048138-0e800ede-9f37-4c18-ba6c-8f0347fc6fef.png)
![image](https://user-images.githubusercontent.com/17617821/147048206-4ab85f0a-764e-4b40-8ed3-943ea7f4b3de.png)

**Comment by m-nathani** [comment]
add this code in your .env.production file or .env file:

```GENERATE_SOURCEMAP=false```

More details: https://stackoverflow.com/questions/51984146/how-to-disable-source-maps-for-react-js-application
