### ISSUE TITLE
[Feature] Typescript type definition for craco

### ISSUE THREAD

**Issue by fanck0605** [gsoft-inc/craco#365]
Hello, I found that we can use typescript to write configuration for @craco/craco, but it lacks type definition files to provide code hints for IDE.

So, I have written type definition files ([types/craco__craco](https://github.com/fanck0605/DefinitelyTyped/tree/craco/types/craco__craco)) for craco's configuration files and all the public APIs.

If the project maintainers allow me to do so, I will open a pull request to submit all changes to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Once the PR is merged, everyone can just use `npm install @types/craco__craco` to get the type definition files.

Although I have tested the type definitions in my project, some of the type definitions may still have some potential problems, so I hope somebody can help me review the code to correct them.

**Comment by patricklafrance** [comment]
That’s great, thanks for the contribution :)

**Comment by fanck0605** [comment]
I've already opened a pull request. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57901
