### ISSUE TITLE
How to set env var in craco.config.js?

### ISSUE THREAD

**Issue by hyperknot** [gsoft-inc/craco#368]
I'd like to add `FAST_REFRESH='false'` in CRACO, and I've read here in an other issue that I should be using `setEnvironmentVariable()` for this. I've seen this is in the API, but it is not clear is how can I use the API in `craco.config.js`.

I've searched through the recipes but I couldn't find anything related to environment variables or `overrideDevServer()`?

**Comment by eleven-net-cn** [comment]
https://github.com/toddbluhm/env-cmd#readme
recommend this

**Comment by dilanx** [comment]
In your `package.json`, you can set environment variables when running a script command. Instead of `craco start`, you can do `FAST_REFRESH=false craco start`. The same thing applies for any of the other commands.
