### ISSUE TITLE
Disabling code splitting

### ISSUE THREAD

**Issue by LoganDark** [gsoft-inc/craco#371]
I'm bundling an application for **offline** use, where it's more important that the entire app loads at once and stays in RAM, than it is for it to load quickly over a network connection. How do I use craco to disable code splitting?

**Comment by davea38** [comment]
You need to override the webpack configuration in craco.config.js and modify the webpackConfig.optimization.runtimeChunk and webpackConfig.optimization.splitChunks settings.

Check the webpack project for the required options.

**Comment by davea38** [comment]
See https://github.com/gsoft-inc/craco/issues/336#issuecomment-963215889
