### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by creativiii** [gsoft-inc/craco#375]
You might not be aware of this, but a bug was introduced at some point in `react-scripts` (specifically `react-error-overlay`) facebook/create-react-app#11773.

It causes an `iframe` overlaying the screen to appear when HMR is triggered, which is very annoying during development.

From my research I can see that craco has:
```
 peer react-scripts@"^4.0.0" from @craco/craco@6.4.0
```

Which means the latest version of `react-error-overlay` will always be installed unfortunately.

As an end user I managed to fix this by installing `react-error-overlay@6.0.9`, I'm not sure if you might be able to fix this on Craco by doing the same for the package but it could be worth a try?

Either way, thought I'd mention it here in case someone stumbles upon this same issue.

**Comment by obrm** [comment]
@creativiii FYI, I use craco in my project and I installed react-error-overlay in my project, and I still get the error "Uncaught ReferenceError: process is not defined".

**Comment by creativiii** [comment]
> @creativiii FYI, I use craco in my project and I installed react-error-overlay in my project, and I still get the error "Uncaught ReferenceError: process is not defined".

That's weird. What versions of craco/react-scripts/react-error-overlay do you have installed?

**Comment by mathiusjohnson** [comment]
I am also running into this error after adding `react-error-overlay@6.0.9`, using `"react-scripts": "^4.0.0"` and `"@craco/craco": "^6.4.3"`. Also saw a SO thread about adding 

```
  "resolutions": {
    "react-error-overlay": "6.0.9"
  },
```

to `package.json` which doesn't seem to help..

**Comment by creativiii** [comment]
> I am also running into this error after adding `react-error-overlay@6.0.9`, using `"react-scripts": "^4.0.0"` and `"@craco/craco": "^6.4.3"`. Also saw a SO thread about adding
> 
> ```
>   "resolutions": {
>     "react-error-overlay": "6.0.9"
>   },
> ```
> 
> to `package.json` which doesn't seem to help..

Resolutions only works if you're using `yarn`.

I have `"react-scripts": "4.0.1"` and `"@craco/craco": "^6.0.0",` as well as `"react-error-overlay": "6.0.9",` and I'm not experiencing the error.

**Comment by dilanx** [comment]
It looks like since this is just an issue with CRA, any solution for the problem here would be the same as the one in the linked issue. It doesn't seem like this issue is craco specific, so your best bet would probably be to wait until progress is made on their end (and use the working version of react-error-overlay until then).
