### ISSUE TITLE
Could this be a bug?

### ISSUE THREAD

**Issue by liujiayii** [gsoft-inc/craco#376]
when I use craco and react-scripts@5,
![image](https://user-images.githubusercontent.com/38902744/148802605-bdc093af-6858-4730-bbd6-cced18530e97.png)
I guess this may have caused the problem?
![image](https://user-images.githubusercontent.com/38902744/148803003-ad4c9242-0d01-4650-92e4-ca06de808585.png)

**Comment by tom-ricci** [comment]
#353

**Comment by patricklafrance** [comment]
Duplicate of https://github.com/gsoft-inc/craco/issues/378
