### ISSUE TITLE
Upgrade for React Scripts V5

### ISSUE THREAD

**Issue by rmcarias** [gsoft-inc/craco#377]
When will you all be updating this package to be compatible with V5 of react-scripts?
Right now if you update react-scripts to v5, it works, but throws the NPM warning because of the peer Dependency.

Additional context: The upgrade is important as react-scripts v5 has an update to immer which addresses a critical security flaw.

**Comment by CowDotDev** [comment]
Duplicate of: https://github.com/gsoft-inc/craco/issues/353

**Comment by patricklafrance** [comment]
Duplicate of https://github.com/gsoft-inc/craco/issues/378
