### ISSUE TITLE
Visual Studio

### ISSUE THREAD

**Issue by jgwinner** [gsoft-inc/craco#379]
Is there a way to run craco with Visual Studio?

(Visual Studio, not Visual Studio Code, but that wouldn't hurt either)

If there is, can we add that to the Readme?

Thanks for any advice.

**Comment by dilanx** [comment]
You should be able to run craco from the command line if you set up your scripts correctly in your package.json (see [Installation](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#installation)).

If you're looking for an extension that runs npm scripts within Visual Studio, I found this online: https://github.com/madskristensen/NpmTaskRunner
