### ISSUE TITLE
Hot reload is not working for JSON inside .js file

### ISSUE THREAD

**Issue by Nefcanto** [gsoft-inc/craco#380]
Hi

In my application hot reload works for every component. But I also have some `.js` files that contain JSON inside them, and the hot reload is not working for them.

For example, I have this JSON array that is used to create the sharing menu:

```
const sharingItems = [
    {
          "title": "Facebook",
          "icon": FacebookIcon,
          "url": "url_to_share_on_facebook"
    },
    {
          "title": "Twitter",
          "icon": TwitterIcon,
          "url": "url_to_share_on_twitter"
    }
]
```

And I use it in my component this way:

```
import sharingItems from '../data/SharingItems'

const SharingMenu = () => {
     return <div>
           {
                 sharingItems.map(item => <span>
                        {
                                <a href={item.url} target='_blank'>{item.title}</a>
                        }
                 </span>)
           }
    </div>
}
```

When I change the `SharingItem.js` content/JSON, I don't see any changes in UI. I need to stop my application and restart it.

**Comment by dilanx** [comment]
I can't seem to recreate your issue. I had a file for the data and a file for the component which imported the data. When I made any modifications to the data, hot reload worked as expected. Feel free to leave a comment if you're still experiencing this issue.
