### ISSUE TITLE
Upgrading to 7.0.0-alpha.0 breaks babel jest plugins

### ISSUE THREAD

**Issue by bgirard** [gsoft-inc/craco#393]
Here's a minimal repo that reproduces the issue:
https://github.com/bgirard/craco-formatjs

First is a base commit on craco 6.4.3 + react-scripts 4.0.3 with a working `yarn test` command:
https://github.com/bgirard/craco-formatjs/commit/3618b303fc7b84a655079401fcf83ecf69b8c332#:~:text=%40craco/craco%22%3A%20%22%5E6.4.3

Then here's a minimal commit to upgrade to craco 7.0.0-alpha.0 and react-scripts 5.0.0 where `yarn test` no longer works:
https://github.com/bgirard/craco-formatjs/commit/e36487fa7fbf479040801f9d1db2a3036f5c1347

Then for fun I tried to eject and get yarn test working with this PR and it was relatively easy to work:
https://github.com/bgirard/craco-formatjs/pull/1/files#r808293292

Speculating on the root cause. It might have to do with:
create-jest-babel-transform.js not getting a `cracoConfig` and thus skipping the addPlugins steps.

**Comment by bgirard** [comment]
I was able to side-step the issues without ejecting by replacing CRACO's jest transform:
```
        jestConfig.transform = { 
          '\\.[jt]sx?$': ['babel-jest', { configFile: './jest.babel.config.js' }], 
          ...jestConfig.transform,
        }; 
```

**Comment by patricklafrance** [comment]
Hi @bgirard thanks for the issue.

You're right, it's an issue with the transform code not getting `cracoConfig`. It's been fix in https://github.com/gsoft-inc/craco/tree/cra5_jest_cracoconfig_access but not released yet.

Will try to release it ASAP.

**Comment by patricklafrance** [comment]
Should be fixed with https://github.com/gsoft-inc/craco/releases/tag/v7.0.0-alpha.3
