### ISSUE TITLE
How to prevent moment.js from loading locales with Craco?

### ISSUE THREAD

**Issue by devGitAbhishek** [gsoft-inc/craco#400]
I want to avoid loading all locales for moment which will help me in reducing build size of app.

**Comment by m-nathani** [comment]
This question is more related how you are using your moment **imports**. 

**Hint**: check [tree shaking](https://webpack.js.org/guides/tree-shaking/)


Further details: in `craco.config.js` , you can override the plugins and ignore 
```js
const webpack = require('webpack');
module.exports = {
   plugins: [
      // Ignore all locale files of moment.js
      new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
   ],
};
```
load specific locales in your code.
```js
const moment = require('moment');
require('moment/locale/ja');
moment.locale('ja');
 ```
