### ISSUE TITLE
Exclude a path from applying postcss rules on it

### ISSUE THREAD

**Issue by arianshahalami** [gsoft-inc/craco#402]
## Problem
Not able to apply postcss on a specific path

## Description
Im using React and craco@v6.alpha. in postcssOptions I use postcss-rtlcss plugin which makes styles rtl. I'm using a template which I dont want to to apply postcss-rtlcss on it. but I couldn't find a way to exclude a path in postcss, craco or postcss-rtlcss configs. any idea?

## My craco config

```
const postCssRtl = require("postcss-rtlcss");

module.exports = {
    reactScriptsVersion: "react-scripts",
    style: {
        postcss: {
            loaderOptions: {
                postcssOptions: { 
                    plugins: [postCssRtl()],
                },
            },
        },
    },
};
```

**Comment by dilanx** [comment]
Try using [postcss-exclude-files](https://www.npmjs.com/package/postcss-exclude-files) to get this behavior. You can configure webpack within your craco config. I'll close this issue but feel free to leave a comment if you're still having this problem.
