### ISSUE TITLE
Verbose is not verbose enough

### ISSUE THREAD

**Issue by thany** [gsoft-inc/craco#405]
When I build with the `--verbose` flag, it does output verbosely. After that, it says "Creating an optimized production build..." and that's where any form of verbosity ends in complete brevity.

To diagnose any problems that aren't errors, perhaps performance during compilation or what have you, the compilation step also needs to be verbose. That's what I'm asking for by adding the `--verbose` argument.

Now, I have noticed in the documentation that it's possible to add a webpack.config.js and do additional stuff there:
https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#webpack-api
(I haven't actually tried this though)

But is that really the way to go? Surely it can't be too difficult for a `--verbose` argument to get passed down to CRA and webpack automagically?

Disclaimer: I'm not trying to solve an actual problem right now. I just noticed the lack of verbosity when asking for it.

**Comment by patricklafrance** [comment]
If CRA have such a argument, why not!

**Comment by thany** [comment]
I don't know if it does, I haven't used CRA without CO 😀
