### ISSUE TITLE
How to create a development build?

### ISSUE THREAD

**Issue by pguardiario** [gsoft-inc/craco#411]
`craco build` is ignoring my NODE_ENV

**Comment by Zsynuting** [comment]
having the same problem
watch this issue

**Comment by dilanx** [comment]
According to the [CRA docs on environment variables](https://create-react-app.dev/docs/adding-custom-environment-variables/), you can't override NODE_ENV manually (it might be possible for the start and test scripts but not for build). However, a super easy alternative is to have a separate environment variable for whatever you need, provided that you prefix it with `REACT_APP_`.
