### ISSUE TITLE
Craco CLI always returns zero exit code in Docker

### ISSUE THREAD

**Issue by alyyousuf7** [gsoft-inc/craco#416]
Consider the following case, where `craco.config.ts` throws error for any reason. I expect `craco build` command to return non-zero error - and it in fact does return non-zero error normally.

However, if I run the same to build Docker image, it shows the error on console, but the command still somehow returns zero exit code.

`craco.config.ts`
```js
throw new Error('Hello world');
```

`Dockerfile`
```Dockerfile
FROM node:14.17.6-slim

WORKDIR /code

COPY package*.json ./
RUN npm ci --no-optional

COPY . .
RUN npx craco build

# it always reaches this point and always returns 0 and the `build` folder doesn't exists
RUN echo $?
```

This is not expected. We use Docker to build production image

**Comment by alyyousuf7** [comment]
I changed the base image to `node:16:14.2-slim` and it started working as expected in Docker.

This should still be considered as bug for older version of node - but feel free to close it.

**Comment by dilanx** [comment]
Please let me know if further issues arise.
