### ISSUE TITLE
The build process takes to long after installing craco

### ISSUE THREAD

**Issue by vanminhquangtri** [gsoft-inc/craco#418]
Hello,

Fist of all, this library is perfect for me to use global variables scss instead of import variables to each component.

But, it seems that this library cause the build process very slow. It's about 5 minutes. While before use craco, it took only about 10 - 20 seconds. I have searched but there's no useful information found. 

Do you have any advice for this?

I use @craco/craco version 6.4.3.

My codes:

1) package.json: I already changed to below: 
`
"scripts": {
  start": "craco start",
  "build": "craco build"
  "test": "craco test"
}
`

2) craco.config.js:
`
module.exports = {
  style: {
    sass: {
      loaderOptions: {
        additionalData: `
          @import "src/styles/common.scss";
          @import "src/common/Container/index.scss";
        `,
      },
    },
  },
};
`

**Comment by vanminhquangtri** [comment]
No rep provided

**Comment by longnc100500** [comment]
i have the same problem :(
