### ISSUE TITLE
how to disable prettier on save?

### ISSUE THREAD

**Issue by kevzettler** [gsoft-inc/craco#419]
Is there any way to disable prettier on save? It's slowing dev time having to fix whitespace nits on every save iteration.

**Comment by Codex-** [comment]
https://github.com/gsoft-inc/craco/blob/master/.vscode/settings.json#L6

Although I'd recommend leaving it on. If you're experiencing any slow down to a point that you notice it I'd suspect you have a bigger issue locally.
