### ISSUE TITLE
Can we change the NODE_ENV by craco config

### ISSUE THREAD

**Issue by mattchannn** [gsoft-inc/craco#421]
Dear all,

Our team has a monorepo that contains several common modules (API service) and a frontend (CRA with CRACO).
However, there are some places in the common modules that restrict API calls by having `process.env.NODE_ENV !== 'development'`, instead it returns a mock response. However, our team would like to override CRACO settings to set to non-dev mode without touching the common modules which are used by the entire org.

Is there any way we could override `NODE_ENV` for the React app specifically?
Like.. `NODE_ENV=STAGE`

For now I know

1. CRA doesn't allow us to change NODE_ENV directly
2. I could use `.env.local` to add my custom variables. Yet, NODE_ENV is still not changeable

**Comment by m-nathani** [comment]
In my understanding env vars inside react app are nothing more then a plugin that reads the values from `.env` files and inject into `process.env`, 

so what i mean is static builds does not have any node env that reads from process.. if you need to set NODE_ENV, 
you can create your own env like MY_NODE_ENV and use that in all of your mono repo to handle your use case.

Hope i am able to understand your issue correctly.

**Comment by mattchannn** [comment]
> In my understanding env vars inside react app are nothing more then a plugin that reads the values from `.env` files and inject into `process.env`,
> 
> so what i mean is static builds does not have any `node` env that reads from `process`.. if you need to set `NODE_ENV`, you can create your own env like `MY_NODE_ENV` and use that in all of your mono repo to handle your use case.
> 
> Hope i am able to understand your issue correctly.

@m-nathani 

I think I missed something..

1) I could not use a customized env var like "MY_CUSTOM_ENV" because we can't do such drastic change at this point and in fact we don't own the common service's code base, we can only make the change on our side.
2) NODE_ENV is not for production, I agree with the static build thing. The NODE_ENV is just for development's use, when the NODE_ENV is not equal to "PRODUCTION", we mock the response. If it is equal to "PRODUCTION", we fire a network request. In this situation, we would like to manipulate the NODE_ENV to test the network request for integration. With that, we can split the mode into three / even four. "DEVELOPMENT", "SIT", "UAT" and "PRODUCTION".

I finally managed to figure it out. We can use cross-env to override the NODE_ENV with craco config while we couldn't if we just do it on a simple CRA project without CRACO.
