### ISSUE TITLE
Adding babel-plugin-styled-components breaks tests

### ISSUE THREAD

**Issue by kumikumi** [gsoft-inc/craco#427]
Here is a [sample project](https://github.com/kumikumi/babel-plugin-styled-components-craco-tests) with craco and babel-plugin-styled-components. Running "yarn test" produces the following errors:

```
Determining test suites to run...

  ● Test suite failed to run

    TypeError: babelJest.createTransformer is not a function

      at createJestBabelTransform (node_modules/@craco/craco/lib/features/jest/create-jest-babel-transform.js:56:22)
      at Object.<anonymous> (node_modules/@craco/craco/lib/features/jest/jest-babel-transform.js:9:8)
      at node_modules/@jest/transform/build/ScriptTransformer.js:382:73
```

Steps to reproduce:

1. Bootstrap a new application with create-react-app
2. Add stable version of yarn
3. Add craco
4. Add babel-plugin-styled-components to craco.config.js
5. "yarn test"

**Comment by dilanx** [comment]
The latest release of craco doesn't support CRA 5 yet, so that's probably why you got that error. I tried running your sample project's tests with the latest alpha version of craco and it worked!
