### ISSUE TITLE
Add a flag to prevent craco from overriding CRA babel config for files outside of src

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/craco#49]
See #36 for details

**Comment by tuucan** [comment]
When I add a babel plugin, it breaks IE11 support. Seems like Promise and Object.assign() polyfills are not included. Could that be related?

```
module.exports = {
  babel: {
    plugins: ['@babel/plugin-proposal-optional-chaining'],
  },
};
```

**Comment by patricklafrance** [comment]
I dont think so, this one is about not applying customization to the loader that process the files outside of the source directory.

To give you a proper answer I would need time to investigate how CRA apply the polyfill.

CRACO only appends the plugin:

```

**Comment by patricklafrance** [comment]
@tuucan You can create a separare issue if you think this is a CRACO bug
